<?php

use GuiaLocaliza\Companies\Admin\Domains\Models\Category\Category;
use Illuminate\Database\Seeder;

class CategoriesTableSedeer extends Seeder
{
    /**
     * @var Category
     */
    private $category;

    /**
     * CategoriesTableSedeer constructor.
     * @param Category $category
     */
    public function __construct(Category $category)
    {
        $this->category = $category;
    }

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $total = $this->category->count();
        $categories = $this->categories();

        if($total === count($categories)) {
            return;
        }

        if($total <= 0) {

            foreach ($categories as $category) {
                $this->category->create([
                    'id' => $category['id'],
                    'name' => $category['name'],
                    'active' => true
                ]);
            }
            return;

        }

        foreach ($categories as $category) {

            $total = $this->category->where('name', $category['name'])->count();
            if ($total <= 0) {
                $this->category->create([
                    'id' => $category['id'],
                    'name' => $category['name'],
                    'active' => true
                ]);
            }

        }

        return;
    }

    private function categories()
    {
        return array(
            array('id' => '1','name' => 'Transportes de Valores'),
            array('id' => '18','name' => 'Serviços de Borracharias e Borracheiros'),
            array('id' => '20','name' => 'Consultoria em Arquitetura e Engenharia Civil'),
            array('id' => '21','name' => 'Lojas de Materiais de Construção'),
            array('id' => '24','name' => 'Aluguel de Artigos e Equipamentos para Eventos e Festas'),
            array('id' => '25','name' => 'Desenvolvimento de Sistemas e Tecnologia da Informação'),
            array('id' => '26','name' => 'Transportes de Passageiros, Viagens e Turismo'),
            array('id' => '28','name' => 'Lojas de Móveis e Eletrodomésticos'),
            array('id' => '34','name' => 'Turismo de Aventura, Turismo Ecológico e Turismo Rural'),
            array('id' => '35','name' => 'Assessoria Imobiliárias e Corretoras de Imóveis'),
            array('id' => '36','name' => 'Agências, Garagens e Concessionárias de Automóveis'),
            array('id' => '39','name' => 'Agências Bancárias e Bancos'),
            array('id' => '40','name' => 'Serviços Gerais'),
            array('id' => '41','name' => 'Distribuidores de Combustíveis'),
            array('id' => '43','name' => 'Transportes de Cargas, Encomendas e Mercadorias em Geral'),
            array('id' => '44','name' => 'Cooperativas em Geral'),
            array('id' => '45','name' => 'Comércio de Armarinhos e Aviamentos'),
            array('id' => '46','name' => 'Órgãos Públicos'),
            array('id' => '48','name' => 'Auto Elétricas'),
            array('id' => '49','name' => 'Insumos e Produtos Agrícolas'),
            array('id' => '55','name' => 'Atendimento Fast Food'),
            array('id' => '56','name' => 'Salão de Beleza e Cabeleireiros'),
            array('id' => '58','name' => 'Associação Cultural, Desportiva, Social, Beneficiente, Beneficente, Filantrópica'),
            array('id' => '59','name' => 'Viveiros de Plantas'),
            array('id' => '60','name' => 'Vidraçarias'),
            array('id' => '62','name' => 'Sex Shop'),
            array('id' => '63','name' => 'Gravação de Placas'),
            array('id' => '64','name' => 'Auto Escolas'),
            array('id' => '67','name' => 'Aluguel de Carros'),
            array('id' => '68','name' => 'Locadora de Filmes, Jogos e Videolocadoras'),
            array('id' => '69','name' => 'Papelarias'),
            array('id' => '70','name' => 'Assessoria e Consultoria em Agronegócios'),
            array('id' => '73','name' => 'Peixarias'),
            array('id' => '74','name' => 'Padarias, Panificadoras e Confeitarias'),
            array('id' => '77','name' => 'Postos de Combustíveis'),
            array('id' => '78','name' => 'Autopeças e Acessórios Automotivos'),
            array('id' => '79','name' => 'Serviços Metalúrgicos, Serralherias, Calhas e Rufos'),
            array('id' => '80','name' => 'Cooperativas de Créditos'),
            array('id' => '81','name' => 'Institutos e Fundações'),
            array('id' => '82','name' => 'Associações Comerciais e Empresariais'),
            array('id' => '84','name' => 'Auto Center e Oficina Mecânica para Automóvel'),
            array('id' => '85','name' => 'Sorveterias'),
            array('id' => '86','name' => 'Agências de Viagens e Turismo'),
            array('id' => '87','name' => 'Academias de Ginástica'),
            array('id' => '88','name' => 'Comércios de Açougues, Casas de Carnes e Frigoríficos'),
            array('id' => '89','name' => 'Clínicas e Consultórios de Fisioterapias'),
            array('id' => '90','name' => 'Escritórios de Advocacias e Advogados'),
            array('id' => '91','name' => 'Distribuidores de Água e Gás'),
            array('id' => '93','name' => 'Atelier de Costuras e Alfaiates'),
            array('id' => '94','name' => 'Comércio e Aluguel de Andaimes'),
            array('id' => '95','name' => 'Comércio e Instalação de Antenas e Parabólicas'),
            array('id' => '97','name' => 'Atelier de Artesanatos'),
            array('id' => '98','name' => 'Lojas de Artigos Religiosos'),
            array('id' => '99','name' => 'Planos e Convênios de Saúde'),
            array('id' => '102','name' => 'Táxi Aéreo'),
            array('id' => '103','name' => 'Artigos e Equipamentos para Balanças'),
            array('id' => '104','name' => 'Aeroportos'),
            array('id' => '105','name' => 'Comércio e Aluguel de Banheiros Químicos'),
            array('id' => '106','name' => 'Distribuidores de Bebidas'),
            array('id' => '107','name' => 'Bibliotecas'),
            array('id' => '108','name' => 'Bicicletarias'),
            array('id' => '109','name' => 'Comércio de Bijuterias'),
            array('id' => '111','name' => 'Boates, Danceterias e Night Clubs'),
            array('id' => '112','name' => 'Comércios de Bordados'),
            array('id' => '115','name' => 'Buffet e Salões para Eventos e Festas'),
            array('id' => '117','name' => 'Lojas de Calçados'),
            array('id' => '118','name' => 'Serviços de Reforma de Colchões'),
            array('id' => '120','name' => 'Câmaras Municipais'),
            array('id' => '121','name' => 'Carimbos e Carimbarias'),
            array('id' => '122','name' => 'Administração de Cartões de Créditos'),
            array('id' => '123','name' => 'Cartórios e Tabeliães'),
            array('id' => '124','name' => 'Casas Lotéricas'),
            array('id' => '125','name' => 'Cerâmicas e Olarias'),
            array('id' => '126','name' => 'Chaveiros'),
            array('id' => '127','name' => 'Cinemas'),
            array('id' => '128','name' => 'Clínicas de Radiologia e Diagnósticos por Imagem'),
            array('id' => '130','name' => 'Clínicas, Consultórios e Centro Médicos em Geral'),
            array('id' => '133','name' => 'Clínicas e Consultórios Veterinários'),
            array('id' => '134','name' => 'Clubes Sociais e Recreativos'),
            array('id' => '135','name' => 'Lojas de Colchões'),
            array('id' => '136','name' => 'Colonizadoras'),
            array('id' => '137','name' => 'Administradoras de Consórcios'),
            array('id' => '138','name' => 'Construtoras e Empreiteiras'),
            array('id' => '139','name' => 'Consulados e Embaixadas'),
            array('id' => '140','name' => 'Escritório Contábil e Contabilidade'),
            array('id' => '141','name' => 'Fotocópias e Fotocopiadoras'),
            array('id' => '142','name' => 'Serviços de Decoração'),
            array('id' => '143','name' => 'Berçários e Creches'),
            array('id' => '144','name' => 'Peças e Assistência Técnica para Eletrodomésticos'),
            array('id' => '146','name' => 'Limpezas de Fossas e Desentupidoras'),
            array('id' => '147','name' => 'Dedetização, Dedetizadoras e Desinsetizadora'),
            array('id' => '148','name' => 'Delegacias de Polícias'),
            array('id' => '149','name' => 'Despachantes em Geral'),
            array('id' => '150','name' => 'Docerias, Doces e Salgados'),
            array('id' => '151','name' => 'Eletrônicas e Assistências Técnicas'),
            array('id' => '152','name' => 'Eletrotécnicas, Eletrotécnicos e Eletromecânicas'),
            array('id' => '155','name' => 'Lojas de Som e Vídeos'),
            array('id' => '156','name' => 'Marcenarias e Móveis Planejados'),
            array('id' => '157','name' => 'Comércio e Distribuição de Embalagens'),
            array('id' => '158','name' => 'Agências de Empregos'),
            array('id' => '159','name' => 'Aluguel de Caçambas e Coletas de Entulhos e Containers'),
            array('id' => '161','name' => 'Escolas de Cursos Técnicos Profissionalizantes'),
            array('id' => '163','name' => 'Escolas e Colégios Públicas'),
            array('id' => '165','name' => 'Universidades e Faculdades'),
            array('id' => '167','name' => 'Escolas e Colégios Particulares'),
            array('id' => '168','name' => 'Escolas de Danças'),
            array('id' => '169','name' => 'Escolas de Idiomas e Línguas'),
            array('id' => '170','name' => 'Conservatórios e Escolas de Música'),
            array('id' => '172','name' => 'Estacionamentos'),
            array('id' => '173','name' => 'Casas de Shows e Espetáculos'),
            array('id' => '174','name' => 'Hidrantes e Extintores de Incêndios'),
            array('id' => '175','name' => 'Factoring e Fomento Mercantil'),
            array('id' => '176','name' => 'Fabricação de Tintas'),
            array('id' => '177','name' => 'Drogarias, Farmácias de Manipulação e Produtos Homeopáticos'),
            array('id' => '178','name' => 'Equipamentos e Máquinas para Supermercados'),
            array('id' => '180','name' => 'Ferro Velho'),
            array('id' => '181','name' => 'Filtros e Purificadores de Água'),
            array('id' => '182','name' => 'Financeiras'),
            array('id' => '183','name' => 'Clínicas e Consultórios de Fonoaudiologia'),
            array('id' => '185','name' => 'Fotos e Fotografias e Revelações'),
            array('id' => '186','name' => 'Shopping Popular e Centros Comerciais Popular'),
            array('id' => '187','name' => 'Funilarias e Pinturas Automotivas'),
            array('id' => '188','name' => 'Frigoríficos Industrial em Geral'),
            array('id' => '189','name' => 'Funerárias e Túmulos'),
            array('id' => '190','name' => 'Serviços e Comércio de Gessos'),
            array('id' => '191','name' => 'Gráficas e Comunicação Visual'),
            array('id' => '192','name' => 'Editoras e Publicações'),
            array('id' => '193','name' => 'Shopping Center'),
            array('id' => '194','name' => 'Guinchos e Reboques'),
            array('id' => '195','name' => 'Guias de Informações'),
            array('id' => '196','name' => 'Clínicas Hospitalar e Hospitais em Geral'),
            array('id' => '197','name' => 'Hotel, Pousadas'),
            array('id' => '198','name' => 'Igrejas e Templos Religiosos'),
            array('id' => '199','name' => 'Seminários, Congregações, Institutos, Entidades e Organizações Religiosas'),
            array('id' => '201','name' => 'Importação e Exportação de Produtos e Serviços'),
            array('id' => '202','name' => 'Lan Houses, Cyber Cafrés e Centros de Inclusão Digital'),
            array('id' => '203','name' => 'Lojas de Instrumentos Musicais'),
            array('id' => '204','name' => 'Óticas, Relojoarias e Joalherias'),
            array('id' => '205','name' => 'Jornais, Revistas e Revistarias'),
            array('id' => '206','name' => 'Laboratórios de Análises Clínicas'),
            array('id' => '208','name' => 'Lavanderias'),
            array('id' => '209','name' => 'Hidráulicas, Serviços de Freios, Direção e Peças em Geral'),
            array('id' => '210','name' => 'Depósitos de Madeiras, Madeireiras e Serrarias'),
            array('id' => '211','name' => 'Malharias e Confecções de Roupas'),
            array('id' => '212','name' => 'Marmitarias, Marmitas e Marmitex'),
            array('id' => '213','name' => 'Marmorarias'),
            array('id' => '214','name' => 'Hidráulicas, Serviços e Peças em Geral'),
            array('id' => '215','name' => 'Clínicas e Consultórios de Psicologia e Psicólogos'),
            array('id' => '217','name' => 'Motel'),
            array('id' => '218','name' => 'Moto Táxi e Motoboy'),
            array('id' => '219','name' => 'Oficina Mecânica para Motos'),
            array('id' => '220','name' => 'Artigos e Equipamentos para Piscinas'),
            array('id' => '221','name' => 'Serviços de Limpezas de Piscinas'),
            array('id' => '222','name' => 'Placas para Veículos'),
            array('id' => '224','name' => 'Construção e Manutenção de Poços Artesianos'),
            array('id' => '226','name' => 'Polícias e Policiais'),
            array('id' => '228','name' => 'Clubes de Campos e Camping'),
            array('id' => '230','name' => 'Pregão e Comércio de Móveis e Artigos Usadoss'),
            array('id' => '231','name' => 'Pronto Socorro'),
            array('id' => '233','name' => 'Protéticos e Próteses Dentárias'),
            array('id' => '234','name' => 'Venda e Manutenção de Radiadores'),
            array('id' => '235','name' => 'Emissoras de Rádio'),
            array('id' => '236','name' => 'Comércio, Instalação e Manutenção de Refrigeração e Climatização'),
            array('id' => '237','name' => 'Comércio de Carrinhos para Supermercados'),
            array('id' => '238','name' => 'Comércios e Representações Comerciais'),
            array('id' => '239','name' => 'Atacados e Atacadistas'),
            array('id' => '242','name' => 'Bares, Choperias e Cervejarias'),
            array('id' => '243','name' => 'Retífica de Motores'),
            array('id' => '245','name' => 'Estações e Terminais Rodoviários'),
            array('id' => '246','name' => 'Lojas de Roupas e Vestuários em Geral'),
            array('id' => '247','name' => 'Serviços de Água e Esgoto'),
            array('id' => '248','name' => 'Sapatarias e Sapateiros'),
            array('id' => '249','name' => 'Saunas'),
            array('id' => '251','name' => 'Serviços de Som e Iluminação'),
            array('id' => '253','name' => 'Mercados, Supermercados, Hipermercados, Mercearias, Empórios'),
            array('id' => '256','name' => 'Tapeçarias e Tapeceiros'),
            array('id' => '257','name' => 'Tatuagem e Piercings'),
            array('id' => '258','name' => 'Pontos de Táxi e Taxistas'),
            array('id' => '259','name' => 'Lojas de Tecidos em Geral'),
            array('id' => '260','name' => 'TV por Assinatura'),
            array('id' => '261','name' => 'Emissoras de Televisão'),
            array('id' => '262','name' => 'Aluguel de Máquinas Pesadas e Serviços de Terraplanagem e Aterros'),
            array('id' => '264','name' => 'Tornos e Tornearias'),
            array('id' => '266','name' => 'Transportes Aéreos e Companhias Aéreas'),
            array('id' => '267','name' => 'Peças, Máquinas e Implementos Agrícolas'),
            array('id' => '268','name' => 'Produtoras e Editoras de Vídeos'),
            array('id' => '269','name' => 'Comércio e Serviços de Equipamentos de Segurança Eletrônica e Monitoramento'),
            array('id' => '270','name' => 'Serviços de Jardinagem e Paisagismo'),
            array('id' => '272','name' => 'Sítios, Chácaras e Fazendas'),
            array('id' => '274','name' => 'Hospedagem de Sites e Vendas de Domínios'),
            array('id' => '275','name' => 'Sites e Portais de Notícias'),
            array('id' => '276','name' => 'Sindicatos e Federações'),
            array('id' => '277','name' => 'Lojas de Conveniência'),
            array('id' => '278','name' => 'Comércio e Indústria de Nutrição Animal'),
            array('id' => '279','name' => 'Convênios de Crédito Consignado em Folha'),
            array('id' => '281','name' => 'Estúdios de Som e Gravação'),
            array('id' => '282','name' => 'Locutor e Comunicador'),
            array('id' => '284','name' => 'Provedores de Internet e Banda Larga'),
            array('id' => '286','name' => 'Escolas de Futebol'),
            array('id' => '287','name' => 'Comércio e Distribuição de Tintas Industriais'),
            array('id' => '288','name' => 'Sistemas de Energia Solar'),
            array('id' => '289','name' => 'Clínicas e Consultórios de Nutrição e Nutricionistas'),
            array('id' => '290','name' => 'Sistemas e Manutenção de Aquecedor Solar'),
            array('id' => '291','name' => 'Eletricistas, Instalações e Manutenções Elétricas'),
            array('id' => '292','name' => 'Elétricas e Eletrificações'),
            array('id' => '293','name' => 'Piscicultura e Alevinos'),
            array('id' => '294','name' => 'Assistência Técnica para Celulares'),
            array('id' => '295','name' => 'Comércio de Celulares e Acessórios'),
            array('id' => '296','name' => 'Comércio de Tintas Automotivas'),
            array('id' => '299','name' => 'Comércio de Pneus Novos e Recauchutados'),
            array('id' => '304','name' => 'Algodoeiras'),
            array('id' => '305','name' => 'Comércio e Indústria de Biodiesel'),
            array('id' => '306','name' => 'Agências de Publicidade, Propagandas e Marketing'),
            array('id' => '307','name' => 'Comércio de Mangueiras e Acoplamentos Pneumáticos'),
            array('id' => '308','name' => 'Lojas Utensílios e Utilidades Domésticas'),
            array('id' => '309','name' => 'Suplementos Alimentares'),
            array('id' => '310','name' => 'Pedreiros'),
            array('id' => '311','name' => 'Comércio de Peças e Assistência para Motosserra'),
            array('id' => '313','name' => 'Clínicas e Consultórios Ortopédicos'),
            array('id' => '315','name' => 'Lubrificantes Automotivos'),
            array('id' => '316','name' => 'Lojas de Tintas e Pinturas'),
            array('id' => '317','name' => 'Comércio de Parafusos e Porcas'),
            array('id' => '321','name' => 'Usinas de Eletricidade'),
            array('id' => '322','name' => 'Agências e Serviços de Recebimentos e Cobranças'),
            array('id' => '323','name' => 'Assessoria Agronômica e Agrônomos'),
            array('id' => '326','name' => 'Instalações de Alarmes e Portões Elétricos'),
            array('id' => '328','name' => 'Cerimonial e Mestre de Cerimônia'),
            array('id' => '330','name' => 'Fábrica de Portas'),
            array('id' => '332','name' => 'Empreendimentos Imobiliários'),
            array('id' => '334','name' => 'Produtos e Equipamentos de Solda'),
            array('id' => '335','name' => 'Comércio e Indústria de Calcários'),
            array('id' => '336','name' => 'Edifícios, Residenciais, Condomínios e Loteamentos'),
            array('id' => '338','name' => 'Escola de Educação Infantil'),
            array('id' => '339','name' => 'Comércio de Baterias Automotivas'),
            array('id' => '342','name' => 'Organização e Promoções de Eventos e Festas'),
            array('id' => '343','name' => 'Equipamentos e Consertos de Máquinas Fotográficas'),
            array('id' => '344','name' => 'Equipamentos e Máquinas para Padarias e Confeitarias'),
            array('id' => '346','name' => 'Apicultura em Geral'),
            array('id' => '347','name' => 'Galeria de Lojas'),
            array('id' => '348','name' => 'Topografia, Agrimensura e Georreferenciamento'),
            array('id' => '349','name' => 'Avicultura de Distribuidores de Ovos'),
            array('id' => '350','name' => 'Assessoria em Projetos Ambientais'),
            array('id' => '352','name' => 'Clínicas de Massoterapia e Massoterapeutas'),
            array('id' => '360','name' => 'Casas de Frios e Laticínios'),
            array('id' => '362','name' => 'Concretos Usinados'),
            array('id' => '363','name' => 'Lojas de Vestidos de Noivas'),
            array('id' => '365','name' => 'Indústria Têxtil'),
            array('id' => '366','name' => 'Aviação Agrícola'),
            array('id' => '368','name' => 'Montagem e Montador de Móveis'),
            array('id' => '369','name' => 'Granjas de Criação de Frangos de Corte'),
            array('id' => '370','name' => 'Peças e Reparos de Embreagens'),
            array('id' => '371','name' => 'Assessoria Previdenciária e Previdência'),
            array('id' => '372','name' => 'Lojas de Produtos para Apicultura'),
            array('id' => '373','name' => 'Telefones Públicos'),
            array('id' => '376','name' => 'Pastelarias'),
            array('id' => '377','name' => 'Tabacarias'),
            array('id' => '378','name' => 'Fábrica de Arames, Telas e Alambrados'),
            array('id' => '379','name' => 'Consultores de Vendas'),
            array('id' => '380','name' => 'Restaurantes Naturalistas'),
            array('id' => '381','name' => 'Pré-Moldados e Artefatos de Cimentos'),
            array('id' => '382','name' => 'Comércio de Forros e Divisórias'),
            array('id' => '383','name' => 'Alarmes Automotivos'),
            array('id' => '384','name' => 'Equipamentos para Usinas de Eletricidade'),
            array('id' => '386','name' => 'Equipamento para Fabricação de Borrachas'),
            array('id' => '387','name' => 'Serviços de Proteção ao Crédito'),
            array('id' => '388','name' => 'Agências de Correios'),
            array('id' => '389','name' => 'Comércio de Pedras e Pedreiras'),
            array('id' => '390','name' => 'Escolas de Informática'),
            array('id' => '391','name' => 'Clínicas e Hospitais Veterinários'),
            array('id' => '392','name' => 'Aluguel de Brinquedos para Festas e Eventos'),
            array('id' => '398','name' => 'Fabricação de Peças para Bicicletas'),
            array('id' => '399','name' => 'Comércio e Distribuição de Oxigênio'),
            array('id' => '400','name' => 'Zootecnia e Zootécnicos'),
            array('id' => '405','name' => 'Adestramento de Cavalos'),
            array('id' => '406','name' => 'Bancos de Sangue'),
            array('id' => '408','name' => 'Comércio e Fabricação de Brindes'),
            array('id' => '409','name' => 'Compra e Venda de Sucatas e Reciclagem em Geral'),
            array('id' => '410','name' => 'Clínica e Consultórios de Oftalmologia'),
            array('id' => '411','name' => 'Clínicas e Consultórios de Dermatologia'),
            array('id' => '413','name' => 'Toldos e Coberturas'),
            array('id' => '414','name' => 'Adestramentos de Cães'),
            array('id' => '415','name' => 'Músicos'),
            array('id' => '416','name' => 'Laboratórios de Análises Ambientais'),
            array('id' => '421','name' => 'Transportes de Mudanças e Fretes'),
            array('id' => '422','name' => 'Fabricação e Consertos de Instrumentos Musicais'),
            array('id' => '423','name' => 'Prefeituras Municipais'),
            array('id' => '424','name' => 'Serviços de Caminhão Munk'),
            array('id' => '425','name' => 'Indústrias e Fábricas de Bebidas'),
            array('id' => '427','name' => 'Laboratórios de Análises Químicas'),
            array('id' => '428','name' => 'Livrarias'),
            array('id' => '429','name' => 'Comércio e Assistência de Transformadores Elétricos'),
            array('id' => '430','name' => 'Transportes Escolar'),
            array('id' => '431','name' => 'Pesqueiros'),
            array('id' => '432','name' => 'Sistemas Agroflorestais e Agroflorestal'),
            array('id' => '433','name' => 'Postos de Saúde'),
            array('id' => '434','name' => 'Portal de Notícias'),
            array('id' => '435','name' => 'Rastreabilidade e Certificadora de Gado'),
            array('id' => '437','name' => 'Comércio e Consertos de Bombas e Compressores'),
            array('id' => '441','name' => 'Loja de Componentes Eletrônicos'),
            array('id' => '443','name' => 'Lojas de Artigos Esportivos'),
            array('id' => '445','name' => 'Comércios de Brinquedos'),
            array('id' => '446','name' => 'Podologias e Podólogos'),
            array('id' => '447','name' => 'Aluguel de Equipamentos para Construções'),
            array('id' => '450','name' => 'Produtos Naturais'),
            array('id' => '453','name' => 'Lojas de Enxoval'),
            array('id' => '458','name' => 'Cerealistas e Beneficiamentos de Alimentos'),
            array('id' => '459','name' => 'Comércio e Fabricação de Cestas de Alimentos'),
            array('id' => '460','name' => 'Adegas de Bebidas'),
            array('id' => '461','name' => 'Artigos e Equipamentos Hospitalares'),
            array('id' => '465','name' => 'Corretores de Valores'),
            array('id' => '467','name' => 'Ateliês de Costuras'),
            array('id' => '468','name' => 'Depósitos de Areias'),
            array('id' => '472','name' => 'Chapas e Perfis de Alumínios'),
            array('id' => '474','name' => 'Lavanderias Hospitalares'),
            array('id' => '475','name' => 'Assistência Técnica Hospitalar'),
            array('id' => '478','name' => 'PENDENTES 2'),
            array('id' => '481','name' => 'Floriculturas'),
            array('id' => '482','name' => 'Escolas de Natação e Hidroginásticas'),
            array('id' => '484','name' => 'Concessionárias e Distribuidoras de Energia Elétrica'),
            array('id' => '485','name' => 'Armazéns Gerais e Silos'),
            array('id' => '486','name' => 'Lojas de Materiais Elétricos em Geral'),
            array('id' => '487','name' => 'Conselho Tutelar'),
            array('id' => '488','name' => 'Clínicas e Consultórios Odontológicos e Dentistas'),
            array('id' => '490','name' => 'Detran e Ciretran'),
            array('id' => '491','name' => 'Clínicas e Consultórios Médicos em Geral'),
            array('id' => '494','name' => 'Manutenção de Equipamentos e Ferramentas Elétricas'),
            array('id' => '495','name' => 'Máquinas e Equipamentos para Marmorarias'),
            array('id' => '496','name' => 'Fórum e Tribunais'),
            array('id' => '499','name' => 'Ginásios de Esportes e Centros de Esportivos'),
            array('id' => '504','name' => 'Oficinas Mecânicas para Caminhões'),
            array('id' => '505','name' => 'Retíficas de Bombas e Bicos Injetores'),
            array('id' => '506','name' => 'Comércio e Instalação de Som Automotivo'),
            array('id' => '507','name' => 'Segurança no Trabalho'),
            array('id' => '508','name' => 'Trios Elétricos e Carros de Som'),
            array('id' => '509','name' => 'Lojas de Cosméticos e Perfumarias'),
            array('id' => '511','name' => 'Títulos de Capitalização'),
            array('id' => '514','name' => 'Procon'),
            array('id' => '515','name' => 'Promotorias de Justiça'),
            array('id' => '517','name' => 'Restaurantes e Churrascarias'),
            array('id' => '518','name' => 'Peças e Acessórios para Motos'),
            array('id' => '520','name' => 'Terapeutas Holísticos'),
            array('id' => '523','name' => 'Portos Marítimos'),
            array('id' => '524','name' => 'Representação Comercial'),
            array('id' => '525','name' => 'Rastreamento de Cargas e Veículos'),
            array('id' => '530','name' => 'Comércio de Café, Chás e Cafeterias'),
            array('id' => '537','name' => 'Suprimentos e Artigos para Padarias e Confeitarias'),
            array('id' => '538','name' => 'PENDENTES 3'),
            array('id' => '539','name' => 'Equipamentos de Segurança'),
            array('id' => '540','name' => 'Clínicas e Consultórios Ginecologia e Ginecologistas'),
            array('id' => '542','name' => 'Transportes Ferroviários'),
            array('id' => '543','name' => 'Produtos de Limpeza e Conservação'),
            array('id' => '544','name' => 'Distribuidores de Doces'),
            array('id' => '545','name' => 'Assessoria e Consultoria Comercial e Empresarial'),
            array('id' => '546','name' => 'Distribuidores de Sorvetes'),
            array('id' => '547','name' => 'Laboratórios de Análises Veterinários'),
            array('id' => '548','name' => 'Casas de Repouso, Asilos, Abrigos, Albergues'),
            array('id' => '552','name' => 'Clínicas e Consultórios de Ortopedia e Ortopedistas'),
            array('id' => '553','name' => 'Cursos Supletivos'),
            array('id' => '556','name' => 'Centro Cultural e Galeria de Arte'),
            array('id' => '557','name' => 'Móveis e Equipamentos para Escritórios'),
            array('id' => '558','name' => 'Cursos Pré-Vestibulares'),
            array('id' => '559','name' => 'Venda e Reforma de Furgões e Carrocerias'),
            array('id' => '560','name' => 'Cursos Preparatórios para Concursos'),
            array('id' => '561','name' => 'Comércio e Fabricação de Temperos e Condimentos'),
            array('id' => '565','name' => 'Cursos de Recrutamento e Seleção'),
            array('id' => '567','name' => 'Corretoras de Seguros e Seguradoras'),
            array('id' => '568','name' => 'Sacolões Hortifrutigranjeiros'),
            array('id' => '570','name' => 'Cursos de Moda, Têxtil e Vestuário'),
            array('id' => '571','name' => 'Cadeias e Presídios'),
            array('id' => '572','name' => 'Cursos de Jardinagem e Paisagismo'),
            array('id' => '573','name' => 'Crédito Imobiliário'),
            array('id' => '574','name' => 'Consultores em Hotelaria e Turismo'),
            array('id' => '575','name' => 'Aluguel de Roupas'),
            array('id' => '578','name' => 'Fabricação e Distribuição de Alarmes'),
            array('id' => '580','name' => 'Pet Shop'),
            array('id' => '581','name' => 'Soluções em Telecomunicações'),
            array('id' => '582','name' => 'Clínicas e Consultórios Neurológicos e Neurologistas'),
            array('id' => '583','name' => 'Compra e Venda de Gado'),
            array('id' => '588','name' => 'Telemensagens'),
            array('id' => '590','name' => 'Lava Jato e Lava Rápido'),
            array('id' => '591','name' => 'Rádio Comunicação'),
            array('id' => '593','name' => 'Produtos Terapêuticos'),
            array('id' => '594','name' => 'Comércio e Fornecimento de Café'),
            array('id' => '595','name' => 'Lojas de Chocolates e Chocolatarias'),
            array('id' => '596','name' => 'Produtos para Caça e Pesca'),
            array('id' => '597','name' => 'Selarias'),
            array('id' => '598','name' => 'Atacado e Fabricação de Enxovais'),
            array('id' => '599','name' => 'Enxovais para Bebês'),
            array('id' => '600','name' => 'Comércio de Roupas Usadas e Brechós'),
            array('id' => '601','name' => 'Conselhos de Classe Profissional'),
            array('id' => '604','name' => 'Comércio e Assistência Técnica de Informática'),
            array('id' => '605','name' => 'Cursos de Formação Técnica'),
            array('id' => '606','name' => 'Defensorias Públicas'),
            array('id' => '610','name' => 'Comércio de Produtos de Camping'),
            array('id' => '611','name' => 'Comércio de Ferramentas Pneumáticas'),
            array('id' => '612','name' => 'Comércio de Peças de Borrachas'),
            array('id' => '613','name' => 'Comércio de Máquinas e Ferramentas em Geral'),
            array('id' => '616','name' => 'Comércio de Equipamentos para Hidráulicas'),
            array('id' => '617','name' => 'Comércio de Bolsas e Malas'),
            array('id' => '618','name' => 'Cestas de Café da Manhã'),
            array('id' => '620','name' => 'Cercas Elétricas'),
            array('id' => '621','name' => 'Espetinhos e Espetarias'),
            array('id' => '622','name' => 'Refrigeração Automotiva'),
            array('id' => '625','name' => 'Equipamentos para Bilhar e Sinuca'),
            array('id' => '628','name' => 'Compensados e Laminados'),
            array('id' => '629','name' => 'Certificadoras Digital'),
            array('id' => '630','name' => 'Terceirização de Serviços'),
            array('id' => '632','name' => 'Correspondentes Bancários'),
            array('id' => '633','name' => 'Equipamentos e Acessórios Náuticos'),
            array('id' => '634','name' => 'Transportes de Água e Caminhões Pipa'),
            array('id' => '635','name' => 'Beneficiamentos de Borrachas'),
            array('id' => '637','name' => 'Aterros Sanitários'),
            array('id' => '638','name' => 'Atelier de Artes'),
            array('id' => '639','name' => 'Fabricação de Tecidos'),
            array('id' => '640','name' => 'Fabricação de Materiais Elétricos'),
            array('id' => '642','name' => 'Fabricação de Bijuterias'),
            array('id' => '643','name' => 'Atacado e Fabricação de Calçados'),
            array('id' => '644','name' => 'Associação de Classe Profissional'),
            array('id' => '647','name' => 'Transportes Urbanos'),
            array('id' => '648','name' => 'Usinas de álcool e Açúcar'),
            array('id' => '649','name' => 'Venda e Manutenção de Máquinas para Fabricar Sorvetes'),
            array('id' => '650','name' => 'Autovidros e Vidros Automotivos'),
            array('id' => '651','name' => 'Web Designer e Desenvolvimento de Sites'),
            array('id' => '652','name' => 'Administração de Condomínios'),
            array('id' => '653','name' => 'Distribuidores de Medicamentos'),
            array('id' => '655','name' => 'Comércio de Produtos Veterinários e Agropecuários'),
            array('id' => '656','name' => 'Conserto de Bonecas'),
            array('id' => '657','name' => 'Atacado e Fabricação de Confecções Unissex'),
            array('id' => '658','name' => 'Fabricação de Armarinhos e Aviamentos'),
            array('id' => '659','name' => 'Fabrica de Confecções Infantis'),
            array('id' => '660','name' => 'Comércio e Distribuição de Silicone'),
            array('id' => '662','name' => 'Corretor de Confecções e Modas'),
            array('id' => '663','name' => 'Incorporação, Incorporadora e Construtora Imobiliária'),
            array('id' => '665','name' => 'Treinamentos e Cursos para Brigada de Incêndios'),
            array('id' => '667','name' => 'Lanchonetes, Pizzarias, Bares e Fast Food'),
            array('id' => '668','name' => 'Saneamento Básico'),
            array('id' => '669','name' => 'Empresas de Logística'),
            array('id' => '670','name' => 'Fotografia e Filmagem para Festas e Eventos'),
            array('id' => '671','name' => 'Pisos e Revestimentos'),
            array('id' => '672','name' => 'Administração de Empresas'),
            array('id' => '673','name' => 'Assessoria e Consultoria Financeira'),
            array('id' => '674','name' => 'Fabricação e Instalação de Postes'),
            array('id' => '675','name' => 'Administração Agrícola e Pecuária'),
            array('id' => '676','name' => 'Fundições'),
            array('id' => '678','name' => 'Distribuidores de Gelo'),
            array('id' => '679','name' => 'Pintores e Pinturas'),
            array('id' => '680','name' => 'Comércio e Distribuição de Óleos e Lubrificantes Industriais'),
            array('id' => '681','name' => 'Maçonaria e Lojas Maçônicas'),
            array('id' => '682','name' => 'Designer de Interiores e Decoração'),
            array('id' => '683','name' => 'Cartórios Eleitorais'),
            array('id' => '684','name' => 'Indústria, Comércio e Distribuidores de Aço e Metal')
          );
    }
}
