<?php

use GuiaLocaliza\Companies\Admin\Domains\Models\Place\Place;
use Illuminate\Database\Seeder;

class PlacesTableSedeer extends Seeder
{
    /**
     * @var Place
     */
    private $place;

    /**
     * PlacesTableSedeer constructor.
     * @param Place $place
     */
    public function __construct(Place $place)
    {
        $this->place = $place;
    }

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $total = $this->place->count();
        $places = $this->places();

        if($total === count($places)) {
            return;
        }

        if($total <= 0) {

            foreach ($places as $place) {

                $this->place->create([
                    'id' => $place['id'],
                    'city_id' => $place['city_id'],
                    'name' => $place['name'],
                    'active' => $place['active']
                ]);

            }
            return;

        }

        foreach ($places as $place) {

            $total = $this->place->where('name', $place['name'])->count();
            if ($total <= 0) {
                $this->place->create([
                    'id' => $place['id'],
                    'city_id' => $place['city_id'],
                    'name' => $place['name'],
                    'active' => $place['active']
                ]);
            }

        }
    }

    private function places()
    {

        return array(
            array('id' => '15', 'city_id' => '2962', 'name' => 'Av. Des. J. P. F. Mendes', 'active' => '1'),
            array('id' => '16', 'city_id' => '2962', 'name' => 'Rua Benedito Moreira da Silva', 'active' => '1'),
            array('id' => '17', 'city_id' => '2962', 'name' => 'Rua João Batista de Almeida', 'active' => '1'),
            array('id' => '18', 'city_id' => '2962', 'name' => 'Rua Almirante Batista das Neves', 'active' => '1'),
            array('id' => '19', 'city_id' => '2962', 'name' => 'Av. Irmão Miguel Abib', 'active' => '1'),
            array('id' => '20', 'city_id' => '2962', 'name' => 'Av. das Palmeiras', 'active' => '1'),
            array('id' => '21', 'city_id' => '2962', 'name' => 'Rod. Sen. Roberto Campos', 'active' => '1'),
            array('id' => '22', 'city_id' => '2962', 'name' => 'Av. Diamantino', 'active' => '1'),
            array('id' => '23', 'city_id' => '2962', 'name' => 'Rua dos Pinheiros', 'active' => '1'),
            array('id' => '24', 'city_id' => '2962', 'name' => 'Rua Jacarandá', 'active' => '1'),
            array('id' => '25', 'city_id' => '2962', 'name' => 'Rua Monsenhor Doudreneuf', 'active' => '1'),
            array('id' => '26', 'city_id' => '2962', 'name' => 'Av. Padre Edgar Schmith', 'active' => '1'),
            array('id' => '27', 'city_id' => '2962', 'name' => 'Rua dos Esportes', 'active' => '1'),
            array('id' => '28', 'city_id' => '2962', 'name' => 'Rua Ipê', 'active' => '1'),
            array('id' => '29', 'city_id' => '647', 'name' => 'Av. Prefeito Caio', 'active' => '1'),
            array('id' => '30', 'city_id' => '2962', 'name' => 'Rua 3 de Dezembro', 'active' => '1'),
            array('id' => '31', 'city_id' => '6037', 'name' => 'Av. Juscelino Kubitschek', 'active' => '1'),
            array('id' => '32', 'city_id' => '6184', 'name' => 'Av. dos Uirapurus', 'active' => '1'),
            array('id' => '33', 'city_id' => '6184', 'name' => 'Av. dos Canários', 'active' => '1'),
            array('id' => '34', 'city_id' => '6044', 'name' => 'Av. Prefeito João Macaúba', 'active' => '1'),
            array('id' => '36', 'city_id' => '6044', 'name' => 'Av. Rodolfo Rodrigues Silva', 'active' => '1'),
            array('id' => '37', 'city_id' => '6044', 'name' => 'Av. Valentin Peron', 'active' => '1'),
            array('id' => '38', 'city_id' => '6044', 'name' => 'Praça Edgar Araújo', 'active' => '1'),
            array('id' => '40', 'city_id' => '647', 'name' => 'Praça da Independência', 'active' => '1'),
            array('id' => '41', 'city_id' => '647', 'name' => 'Av. Castelo Branco', 'active' => '1'),
            array('id' => '42', 'city_id' => '647', 'name' => 'Av. Dom Pedro I', 'active' => '1'),
            array('id' => '43', 'city_id' => '647', 'name' => 'Rua Mato Grosso', 'active' => '1'),
            array('id' => '44', 'city_id' => '647', 'name' => 'Rua Pedro Pedrossian', 'active' => '1'),
            array('id' => '45', 'city_id' => '647', 'name' => 'Av. Papa Paulo VI', 'active' => '1'),
            array('id' => '46', 'city_id' => '647', 'name' => 'Rua Pedro Nunes Barroso', 'active' => '1'),
            array('id' => '47', 'city_id' => '647', 'name' => 'Rua Joaquim Murtinho', 'active' => '1'),
            array('id' => '48', 'city_id' => '7898', 'name' => 'Av. Coronel Arthur Borges', 'active' => '1'),
            array('id' => '49', 'city_id' => '647', 'name' => 'Rua Gonçalves Ledo', 'active' => '1'),
            array('id' => '51', 'city_id' => '647', 'name' => 'Rua Poaeiros', 'active' => '1'),
            array('id' => '52', 'city_id' => '647', 'name' => 'Av. Presidente Getúlio Vargas', 'active' => '1'),
            array('id' => '54', 'city_id' => '9558', 'name' => 'Rua Virgilio Favetti', 'active' => '1'),
            array('id' => '56', 'city_id' => '647', 'name' => 'Rua Almirante Tamandaré', 'active' => '1'),
            array('id' => '58', 'city_id' => '6184', 'name' => 'Av. das Araras', 'active' => '1'),
            array('id' => '60', 'city_id' => '2932', 'name' => 'Av. Mato Grosso', 'active' => '1'),
            array('id' => '61', 'city_id' => '2932', 'name' => 'Av. Júlio José de Campos', 'active' => '1'),
            array('id' => '62', 'city_id' => '2932', 'name' => 'Av. São Paulo', 'active' => '1'),
            array('id' => '63', 'city_id' => '2932', 'name' => 'Rua 7 de Setembro', 'active' => '1'),
            array('id' => '65', 'city_id' => '6037', 'name' => 'Av. Getúlio Vargas', 'active' => '1'),
            array('id' => '66', 'city_id' => '6037', 'name' => 'Rua Tranquilo Dalla Vecchia', 'active' => '1'),
            array('id' => '67', 'city_id' => '6037', 'name' => 'Rua Osvaldo da Silva Campos', 'active' => '1'),
            array('id' => '68', 'city_id' => '6037', 'name' => 'Rod. BR 163', 'active' => '1'),
            array('id' => '69', 'city_id' => '6037', 'name' => 'Rua Bahia', 'active' => '1'),
            array('id' => '70', 'city_id' => '8830', 'name' => 'Av. Argentina', 'active' => '1'),
            array('id' => '71', 'city_id' => '6037', 'name' => 'Av. Marechal Cândido Rondon', 'active' => '1'),
            array('id' => '72', 'city_id' => '6037', 'name' => 'Av. Mário Abraão Nassarden', 'active' => '1'),
            array('id' => '73', 'city_id' => '6037', 'name' => 'Rua Francisco Severino Peixoto', 'active' => '1'),
            array('id' => '74', 'city_id' => '6044', 'name' => 'Av. Getúlio Lino de Souza', 'active' => '1'),
            array('id' => '75', 'city_id' => '6044', 'name' => 'Rua José Lúcio de Oliveira', 'active' => '1'),
            array('id' => '76', 'city_id' => '6044', 'name' => 'Av. Nicolau Gomes de Souza', 'active' => '1'),
            array('id' => '77', 'city_id' => '6177', 'name' => 'Av. Tiradentes', 'active' => '1'),
            array('id' => '78', 'city_id' => '6177', 'name' => 'Rua Marechal Rondon', 'active' => '1'),
            array('id' => '80', 'city_id' => '6177', 'name' => 'Rua Marechal Deodoro', 'active' => '1'),
            array('id' => '81', 'city_id' => '6177', 'name' => 'Rua Marechal Floriano Peixoto', 'active' => '1'),
            array('id' => '82', 'city_id' => '6177', 'name' => 'Rua Manoel Loureiro', 'active' => '1'),
            array('id' => '83', 'city_id' => '6177', 'name' => 'Rua Dom Aquino Corrêa', 'active' => '1'),
            array('id' => '84', 'city_id' => '6177', 'name' => 'Av. Humberto Castelo Branco', 'active' => '1'),
            array('id' => '87', 'city_id' => '6177', 'name' => 'Rod. BR 163/364', 'active' => '1'),
            array('id' => '88', 'city_id' => '6177', 'name' => 'Rua Lídia Borges', 'active' => '1'),
            array('id' => '89', 'city_id' => '2962', 'name' => 'Av. Colina Azul', 'active' => '1'),
            array('id' => '90', 'city_id' => '6177', 'name' => 'Rua Coronel Pedro Corrêa', 'active' => '1'),
            array('id' => '91', 'city_id' => '6177', 'name' => 'Rua Coronel Antonio Bruno', 'active' => '1'),
            array('id' => '92', 'city_id' => '6184', 'name' => 'Av. Mutum', 'active' => '1'),
            array('id' => '98', 'city_id' => '6184', 'name' => 'Rua das Primaveras', 'active' => '1'),
            array('id' => '99', 'city_id' => '6184', 'name' => 'Perimetral das Samambaias', 'active' => '1'),
            array('id' => '100', 'city_id' => '6184', 'name' => 'Av. dos Beija-Flores', 'active' => '1'),
            array('id' => '101', 'city_id' => '6184', 'name' => 'Av. das Arapongas', 'active' => '1'),
            array('id' => '102', 'city_id' => '2962', 'name' => 'Rua 5', 'active' => '1'),
            array('id' => '103', 'city_id' => '6184', 'name' => 'Av. das Águias', 'active' => '1'),
            array('id' => '104', 'city_id' => '6184', 'name' => 'Rua das Margaridas', 'active' => '1'),
            array('id' => '105', 'city_id' => '6184', 'name' => 'Av. das Emas', 'active' => '1'),
            array('id' => '106', 'city_id' => '6184', 'name' => 'Rua dos Cedros', 'active' => '1'),
            array('id' => '107', 'city_id' => '6184', 'name' => 'Rua das Seringueiras', 'active' => '1'),
            array('id' => '108', 'city_id' => '6184', 'name' => 'Rua dos  Cedros', 'active' => '1'),
            array('id' => '109', 'city_id' => '2962', 'name' => 'Rua 3', 'active' => '1'),
            array('id' => '110', 'city_id' => '2962', 'name' => 'Av. Gilmar Mendes', 'active' => '1'),
            array('id' => '111', 'city_id' => '2962', 'name' => 'Av. Buriti', 'active' => '1'),
            array('id' => '112', 'city_id' => '2962', 'name' => 'Rua dos Eucalíptos', 'active' => '1'),
            array('id' => '113', 'city_id' => '2962', 'name' => 'Av. Municipal', 'active' => '1'),
            array('id' => '114', 'city_id' => '2962', 'name' => 'Av. Conceição', 'active' => '1'),
            array('id' => '115', 'city_id' => '6044', 'name' => 'Rua Ver. Tibúrcio Gomes Portela', 'active' => '1'),
            array('id' => '116', 'city_id' => '6178', 'name' => 'Av. Amos Bernardino Zanchet', 'active' => '1'),
            array('id' => '119', 'city_id' => '8830', 'name' => 'Av. Uruguai', 'active' => '1'),
            array('id' => '120', 'city_id' => '7898', 'name' => 'Rua Coronel Pedro Correia', 'active' => '1'),
            array('id' => '121', 'city_id' => '2962', 'name' => 'Trav. da República', 'active' => '1'),
            array('id' => '122', 'city_id' => '6184', 'name' => 'Rod. da Produção', 'active' => '1'),
            array('id' => '123', 'city_id' => '2962', 'name' => 'Rua Frei Manoel', 'active' => '1'),
            array('id' => '124', 'city_id' => '6044', 'name' => 'Rua Domingos Bezerra de Brito', 'active' => '1'),
            array('id' => '126', 'city_id' => '647', 'name' => 'Rua do Comércio', 'active' => '1'),
            array('id' => '127', 'city_id' => '6037', 'name' => 'Rua Tomé Campos', 'active' => '1'),
            array('id' => '128', 'city_id' => '8340', 'name' => 'Rua Pedro Álvares Cabral', 'active' => '1'),
            array('id' => '130', 'city_id' => '6177', 'name' => 'Praça da Bíblia', 'active' => '1'),
            array('id' => '131', 'city_id' => '2962', 'name' => 'Trav. Comendador Henrique', 'active' => '1'),
            array('id' => '134', 'city_id' => '2962', 'name' => 'Rua Sebastião M. Régis', 'active' => '1'),
            array('id' => '135', 'city_id' => '6184', 'name' => 'Rua dos Beija Flores', 'active' => '1'),
            array('id' => '137', 'city_id' => '2962', 'name' => 'Rua da Caixa D\'Água', 'active' => '1'),
            array('id' => '138', 'city_id' => '2962', 'name' => 'Rua 18 de Setembro', 'active' => '1'),
            array('id' => '139', 'city_id' => '6184', 'name' => 'Rua das Tamareiras', 'active' => '1'),
            array('id' => '140', 'city_id' => '2962', 'name' => 'Rua Marechal Cândido Rondon', 'active' => '1'),
            array('id' => '142', 'city_id' => '2962', 'name' => 'Estrada Antonio Crescêncio de Oliveira', 'active' => '1'),
            array('id' => '143', 'city_id' => '2962', 'name' => 'Rua Cedro Rosa', 'active' => '1'),
            array('id' => '144', 'city_id' => '2962', 'name' => 'Rua Fredolino Vieira de Barros', 'active' => '1'),
            array('id' => '145', 'city_id' => '647', 'name' => 'Praça 07 de Setembro', 'active' => '1'),
            array('id' => '146', 'city_id' => '2932', 'name' => 'Av. Brasil', 'active' => '1'),
            array('id' => '147', 'city_id' => '8830', 'name' => 'Av. Governador Júlio Campos', 'active' => '1'),
            array('id' => '148', 'city_id' => '2962', 'name' => 'Rua das Pitombeiras', 'active' => '1'),
            array('id' => '149', 'city_id' => '2962', 'name' => 'Rua B', 'active' => '1'),
            array('id' => '150', 'city_id' => '2962', 'name' => 'Rod. BR 364', 'active' => '1'),
            array('id' => '151', 'city_id' => '2962', 'name' => 'Rua Pau Brasil', 'active' => '1'),
            array('id' => '155', 'city_id' => '8830', 'name' => 'Rua Santa Catarina', 'active' => '1'),
            array('id' => '156', 'city_id' => '2962', 'name' => 'Rua das Mangabeiras', 'active' => '1'),
            array('id' => '159', 'city_id' => '647', 'name' => 'Av. Presidente Costa e Silva', 'active' => '1'),
            array('id' => '160', 'city_id' => '2932', 'name' => 'Rua José Ferreira Costa', 'active' => '1'),
            array('id' => '161', 'city_id' => '8830', 'name' => 'Rua Espírito Santo', 'active' => '1'),
            array('id' => '164', 'city_id' => '2962', 'name' => 'Rua dos Coqueirais', 'active' => '1'),
            array('id' => '165', 'city_id' => '6184', 'name' => 'Av. das Seriemas', 'active' => '1'),
            array('id' => '166', 'city_id' => '2962', 'name' => 'Rua 2', 'active' => '1'),
            array('id' => '167', 'city_id' => '2962', 'name' => 'Rod. MT 440', 'active' => '1'),
            array('id' => '168', 'city_id' => '2962', 'name' => 'Rua das Camélias', 'active' => '1'),
            array('id' => '171', 'city_id' => '2962', 'name' => 'Av. Mario Ferreira Mendes', 'active' => '1'),
            array('id' => '173', 'city_id' => '2962', 'name' => 'Rua Acelino B. Oliveira', 'active' => '1'),
            array('id' => '174', 'city_id' => '2962', 'name' => 'Rua Araucária', 'active' => '1'),
            array('id' => '176', 'city_id' => '6037', 'name' => 'Praça Gov. Júlio José de Campos', 'active' => '1'),
            array('id' => '177', 'city_id' => '6037', 'name' => 'Rua L', 'active' => '1'),
            array('id' => '178', 'city_id' => '7898', 'name' => 'Praça Manoel Loureiro', 'active' => '1'),
            array('id' => '179', 'city_id' => '2962', 'name' => 'Rua João Sava', 'active' => '1'),
            array('id' => '182', 'city_id' => '8830', 'name' => 'Av. Pedro Coelho Portilho', 'active' => '1'),
            array('id' => '183', 'city_id' => '2962', 'name' => 'Rua das Azaléias', 'active' => '1'),
            array('id' => '184', 'city_id' => '8830', 'name' => 'Av. Siegfried Buss', 'active' => '1'),
            array('id' => '185', 'city_id' => '6037', 'name' => 'Rua J', 'active' => '1'),
            array('id' => '186', 'city_id' => '2962', 'name' => 'Rua Quintino Bocaiúva', 'active' => '1'),
            array('id' => '187', 'city_id' => '2962', 'name' => 'Rua Concórdia', 'active' => '1'),
            array('id' => '188', 'city_id' => '8340', 'name' => 'Rua Dep. Murilo Domingos', 'active' => '1'),
            array('id' => '189', 'city_id' => '2962', 'name' => 'Rod. MT 240', 'active' => '1'),
            array('id' => '190', 'city_id' => '7898', 'name' => 'Rua Pedro Ponve', 'active' => '1'),
            array('id' => '192', 'city_id' => '2962', 'name' => 'Rua das Aroeiras', 'active' => '1'),
            array('id' => '195', 'city_id' => '936', 'name' => 'Rua Liberalino Cassetari', 'active' => '1'),
            array('id' => '196', 'city_id' => '2962', 'name' => 'Rua João Batista das Neves', 'active' => '1'),
            array('id' => '197', 'city_id' => '6184', 'name' => 'Rua das Trimulas', 'active' => '1'),
            array('id' => '198', 'city_id' => '2962', 'name' => 'Trav. Irmã Margarida', 'active' => '1'),
            array('id' => '199', 'city_id' => '2962', 'name' => 'Rua Belo Horizonte', 'active' => '1'),
            array('id' => '200', 'city_id' => '2962', 'name' => 'Rua das Orquídeas', 'active' => '1'),
            array('id' => '201', 'city_id' => '2962', 'name' => 'Rod. MT 121', 'active' => '1'),
            array('id' => '202', 'city_id' => '8830', 'name' => 'Av. Cuiabá', 'active' => '1'),
            array('id' => '203', 'city_id' => '2962', 'name' => 'Rua Cambará', 'active' => '1'),
            array('id' => '204', 'city_id' => '2962', 'name' => 'Av. Dom Alonso', 'active' => '1'),
            array('id' => '205', 'city_id' => '647', 'name' => 'Rua Castro Alves', 'active' => '1'),
            array('id' => '206', 'city_id' => '9558', 'name' => 'Rua Antonio Hortolani (Rua 9)', 'active' => '1'),
            array('id' => '207', 'city_id' => '2932', 'name' => 'Rua Piauí', 'active' => '1'),
            array('id' => '208', 'city_id' => '8830', 'name' => 'Rua Guanabara', 'active' => '1'),
            array('id' => '209', 'city_id' => '2962', 'name' => 'Av. Dom Agostinho Kirsth', 'active' => '1'),
            array('id' => '212', 'city_id' => '6037', 'name' => 'Rua Severino Peixoto', 'active' => '1'),
            array('id' => '215', 'city_id' => '936', 'name' => 'Praça Eliazario Arantes Souza', 'active' => '1'),
            array('id' => '216', 'city_id' => '8830', 'name' => 'Rua Leonildo Bernardes', 'active' => '1'),
            array('id' => '217', 'city_id' => '6037', 'name' => 'Av. Filinto Muller', 'active' => '1'),
            array('id' => '218', 'city_id' => '2962', 'name' => 'Rua Medianeira', 'active' => '1'),
            array('id' => '219', 'city_id' => '8830', 'name' => 'Rua Acre', 'active' => '1'),
            array('id' => '220', 'city_id' => '6178', 'name' => 'Rua São Pedro', 'active' => '1'),
            array('id' => '221', 'city_id' => '2962', 'name' => 'Rua Rui Barbosa', 'active' => '1'),
            array('id' => '222', 'city_id' => '647', 'name' => 'Rua Padre João Bosco', 'active' => '1'),
            array('id' => '223', 'city_id' => '2962', 'name' => 'Rua Paracelso Marcondes', 'active' => '1'),
            array('id' => '226', 'city_id' => '647', 'name' => 'Trav. Diamante', 'active' => '1'),
            array('id' => '228', 'city_id' => '6037', 'name' => 'Rua Alair Soares', 'active' => '1'),
            array('id' => '229', 'city_id' => '6044', 'name' => 'Av. Mascarenhas Moraes', 'active' => '1'),
            array('id' => '231', 'city_id' => '7898', 'name' => 'Av. Otávio Costa', 'active' => '1'),
            array('id' => '232', 'city_id' => '2962', 'name' => 'Trevo Buriti', 'active' => '1'),
            array('id' => '233', 'city_id' => '9157', 'name' => 'Rod. MT 170', 'active' => '1'),
            array('id' => '235', 'city_id' => '9157', 'name' => 'Av. André Antonio Maggi', 'active' => '1'),
            array('id' => '236', 'city_id' => '9157', 'name' => 'Av. Brasil', 'active' => '1'),
            array('id' => '237', 'city_id' => '7898', 'name' => 'Rua Lígia Borges', 'active' => '1'),
            array('id' => '238', 'city_id' => '9157', 'name' => 'Rua São Paulo', 'active' => '1'),
            array('id' => '239', 'city_id' => '9157', 'name' => 'Rua São Luiz', 'active' => '1'),
            array('id' => '241', 'city_id' => '9157', 'name' => 'Av. Olacyr de Moraes', 'active' => '1'),
            array('id' => '242', 'city_id' => '9558', 'name' => 'Rua Saturnino de Paula da Silveira (Rua 30)', 'active' => '1'),
            array('id' => '243', 'city_id' => '9157', 'name' => 'Av. Dourado', 'active' => '1'),
            array('id' => '244', 'city_id' => '9558', 'name' => 'Av. Lions Internacional', 'active' => '1'),
            array('id' => '245', 'city_id' => '9558', 'name' => 'Rua Antonio Bortoloni', 'active' => '1'),
            array('id' => '246', 'city_id' => '9157', 'name' => 'Rua Selene da Cunha', 'active' => '1'),
            array('id' => '247', 'city_id' => '9558', 'name' => 'Av. Ismael J. Nascimento', 'active' => '1'),
            array('id' => '249', 'city_id' => '6184', 'name' => 'Av. José Aparecido Ribeiro', 'active' => '1'),
            array('id' => '250', 'city_id' => '6184', 'name' => 'Av. das Andorinhas', 'active' => '1'),
            array('id' => '252', 'city_id' => '5212', 'name' => 'Rua Realeza', 'active' => '1'),
            array('id' => '253', 'city_id' => '5212', 'name' => 'Av. Amazonas', 'active' => '1'),
            array('id' => '254', 'city_id' => '5212', 'name' => 'Av. Vitória Régia', 'active' => '1'),
            array('id' => '255', 'city_id' => '5212', 'name' => 'Av. Rio Grande do Sul', 'active' => '1'),
            array('id' => '256', 'city_id' => '5212', 'name' => 'Av. Paraná', 'active' => '1'),
            array('id' => '257', 'city_id' => '5212', 'name' => 'Rua Guaporé', 'active' => '1'),
            array('id' => '258', 'city_id' => '5212', 'name' => 'Rua Catuipe', 'active' => '1'),
            array('id' => '259', 'city_id' => '5212', 'name' => 'Rua Santa Fé', 'active' => '1'),
            array('id' => '260', 'city_id' => '5212', 'name' => 'Av. Júlio de Castilho', 'active' => '1'),
            array('id' => '261', 'city_id' => '5212', 'name' => 'Av. da Produção', 'active' => '1'),
            array('id' => '264', 'city_id' => '5212', 'name' => 'Rua Getúio Vargas', 'active' => '1'),
            array('id' => '265', 'city_id' => '5212', 'name' => 'Rua Espumoso', 'active' => '1'),
            array('id' => '266', 'city_id' => '5212', 'name' => 'Rua Amor Perfeito', 'active' => '1'),
            array('id' => '267', 'city_id' => '5212', 'name' => 'Av. Nápoli', 'active' => '1'),
            array('id' => '268', 'city_id' => '5212', 'name' => 'Rua Girua', 'active' => '1'),
            array('id' => '269', 'city_id' => '5212', 'name' => 'Av. Sergipe', 'active' => '1'),
            array('id' => '270', 'city_id' => '5212', 'name' => 'Rua CorbÃa', 'active' => '1'),
            array('id' => '271', 'city_id' => '5212', 'name' => 'Rua dos Narcisos', 'active' => '1'),
            array('id' => '272', 'city_id' => '5212', 'name' => 'Rua dos Bálsamos', 'active' => '1'),
            array('id' => '273', 'city_id' => '5212', 'name' => 'Av. Parná', 'active' => '1'),
            array('id' => '275', 'city_id' => '5212', 'name' => 'Rua Fortaleza', 'active' => '1'),
            array('id' => '276', 'city_id' => '5212', 'name' => 'Rua Passo Fundo', 'active' => '1'),
            array('id' => '277', 'city_id' => '5212', 'name' => 'Rua Chapecó', 'active' => '1'),
            array('id' => '278', 'city_id' => '5212', 'name' => 'Rua Palmeira Missões', 'active' => '1'),
            array('id' => '279', 'city_id' => '5212', 'name' => 'Rua Santo Ângelo', 'active' => '1'),
            array('id' => '280', 'city_id' => '5212', 'name' => 'Rua Carazinho', 'active' => '1'),
            array('id' => '281', 'city_id' => '5212', 'name' => 'Rua Cuiabá', 'active' => '1'),
            array('id' => '282', 'city_id' => '5212', 'name' => 'Rua Curitiba', 'active' => '1'),
            array('id' => '283', 'city_id' => '5212', 'name' => 'Rua Cascavel', 'active' => '1'),
            array('id' => '284', 'city_id' => '5212', 'name' => 'Av. Goiás', 'active' => '1'),
            array('id' => '285', 'city_id' => '5212', 'name' => 'Rua Iraí', 'active' => '1'),
            array('id' => '286', 'city_id' => '5212', 'name' => 'Rua Tapera', 'active' => '1'),
            array('id' => '287', 'city_id' => '8830', 'name' => 'Av. João Guilherme Seelent', 'active' => '1'),
            array('id' => '288', 'city_id' => '9157', 'name' => 'Rua Andorinha', 'active' => '1'),
            array('id' => '289', 'city_id' => '6184', 'name' => 'Rua das Castanheiras', 'active' => '1'),
            array('id' => '290', 'city_id' => '9451', 'name' => 'Rua Das Videiras', 'active' => '1'),
            array('id' => '291', 'city_id' => '936', 'name' => 'Av. Rio Branco', 'active' => '1'),
            array('id' => '292', 'city_id' => '6184', 'name' => 'Av. Miguel Sutil', 'active' => '1'),
            array('id' => '293', 'city_id' => '6044', 'name' => 'Av. João Pereira dos Santos', 'active' => '1'),
            array('id' => '294', 'city_id' => '936', 'name' => 'Praça Brasília', 'active' => '1'),
            array('id' => '295', 'city_id' => '9157', 'name' => 'Rua Goiás', 'active' => '1'),
            array('id' => '296', 'city_id' => '9157', 'name' => 'Rua Cará', 'active' => '1'),
            array('id' => '298', 'city_id' => '9451', 'name' => 'Rua Foz do Iguaçu', 'active' => '1'),
            array('id' => '299', 'city_id' => '9558', 'name' => 'Rua Sebastião Barreto (Rua 8)', 'active' => '1'),
            array('id' => '300', 'city_id' => '9451', 'name' => 'Rua Florianópolis', 'active' => '1'),
            array('id' => '301', 'city_id' => '9451', 'name' => 'Av. Tancredo Neves', 'active' => '1'),
            array('id' => '302', 'city_id' => '9451', 'name' => 'Av. Perimetral Sudoeste', 'active' => '1'),
            array('id' => '304', 'city_id' => '9451', 'name' => 'Rod. MT 242', 'active' => '1'),
            array('id' => '305', 'city_id' => '9451', 'name' => 'Av. Natalino João Brescansin', 'active' => '1'),
            array('id' => '306', 'city_id' => '9451', 'name' => 'Rua Mário Spinelli', 'active' => '1'),
            array('id' => '307', 'city_id' => '9558', 'name' => 'Rua São Paulo (Rua 16)', 'active' => '1'),
            array('id' => '308', 'city_id' => '9451', 'name' => 'Rua Tangará', 'active' => '1'),
            array('id' => '309', 'city_id' => '9451', 'name' => 'Av. Perimetral Noroeste', 'active' => '1'),
            array('id' => '310', 'city_id' => '9451', 'name' => 'Av. Blumenau', 'active' => '1'),
            array('id' => '311', 'city_id' => '9451', 'name' => 'Rua Irmã Benedita', 'active' => '1'),
            array('id' => '312', 'city_id' => '9451', 'name' => 'Av. Marginal Direita', 'active' => '1'),
            array('id' => '314', 'city_id' => '9451', 'name' => 'Rua Das Hortências', 'active' => '1'),
            array('id' => '315', 'city_id' => '9451', 'name' => 'Rua Edgar Garcia Siqueira', 'active' => '1'),
            array('id' => '316', 'city_id' => '9451', 'name' => 'Av. Idemar Richer', 'active' => '1'),
            array('id' => '317', 'city_id' => '9451', 'name' => 'Rua Roberto Carlos Braga', 'active' => '1'),
            array('id' => '318', 'city_id' => '9157', 'name' => 'Rua Paraná', 'active' => '1'),
            array('id' => '319', 'city_id' => '6037', 'name' => 'Av. Moacir Parzianello', 'active' => '1'),
            array('id' => '320', 'city_id' => '9558', 'name' => 'Rua Gumercindo Antonietti Marques (Rua 4A)', 'active' => '1'),
            array('id' => '321', 'city_id' => '9157', 'name' => 'Rua Piapara', 'active' => '1'),
            array('id' => '322', 'city_id' => '7898', 'name' => 'Rua Quitino Bocaiúva', 'active' => '1'),
            array('id' => '323', 'city_id' => '9157', 'name' => 'Av. Jaó', 'active' => '1'),
            array('id' => '326', 'city_id' => '6184', 'name' => 'Rua dos Sabiás', 'active' => '1'),
            array('id' => '327', 'city_id' => '9558', 'name' => 'Rua José Florêncio Gudrin (Rua 15)', 'active' => '1'),
            array('id' => '328', 'city_id' => '9558', 'name' => 'Rua Celso Rosa Lima (Rua 26)', 'active' => '1'),
            array('id' => '329', 'city_id' => '9558', 'name' => 'Rua Júlio Martinez Benevides (Rua 11)', 'active' => '1'),
            array('id' => '330', 'city_id' => '6037', 'name' => 'Praça Josino Lopes Serra', 'active' => '1'),
            array('id' => '332', 'city_id' => '9558', 'name' => 'Rod. MT 364', 'active' => '1'),
            array('id' => '335', 'city_id' => '9157', 'name' => 'Rua Piratanta', 'active' => '1'),
            array('id' => '341', 'city_id' => '9558', 'name' => 'Rua Deputado Hitler Sansão (Rua 10)', 'active' => '1'),
            array('id' => '342', 'city_id' => '9558', 'name' => 'Rua José de Oliveira (Rua 28)', 'active' => '1'),
            array('id' => '344', 'city_id' => '9157', 'name' => 'Rua Goiânia', 'active' => '1'),
            array('id' => '345', 'city_id' => '9451', 'name' => 'Rua Genésio Roberto Bagio', 'active' => '1'),
            array('id' => '347', 'city_id' => '6184', 'name' => 'Rua das Oliveiras', 'active' => '1'),
            array('id' => '349', 'city_id' => '9157', 'name' => 'Rua 03 de Junho', 'active' => '1'),
            array('id' => '350', 'city_id' => '9558', 'name' => 'Rua Antonio Barbero Herrero', 'active' => '1'),
            array('id' => '351', 'city_id' => '9157', 'name' => 'Av. Maranhão', 'active' => '1'),
            array('id' => '352', 'city_id' => '6184', 'name' => 'Rua das Figueiras', 'active' => '1'),
            array('id' => '353', 'city_id' => '9157', 'name' => 'Av. Surubim', 'active' => '1'),
            array('id' => '354', 'city_id' => '7898', 'name' => 'Rua Professor Calixto', 'active' => '1'),
            array('id' => '355', 'city_id' => '936', 'name' => 'Av. São Benedito', 'active' => '1'),
            array('id' => '356', 'city_id' => '6044', 'name' => 'Rua Enoque Alves Brito', 'active' => '1'),
            array('id' => '357', 'city_id' => '9157', 'name' => 'Av. Tucunaré', 'active' => '1'),
            array('id' => '358', 'city_id' => '6184', 'name' => 'Rua das Palmeiras', 'active' => '1'),
            array('id' => '361', 'city_id' => '7898', 'name' => 'Rua Doutor Murtinho', 'active' => '1'),
            array('id' => '363', 'city_id' => '9157', 'name' => 'Rua Pirambóia', 'active' => '1'),
            array('id' => '364', 'city_id' => '9558', 'name' => 'Rua João Prado Arantes (Rua 14)', 'active' => '1'),
            array('id' => '365', 'city_id' => '936', 'name' => 'Av. Hitler Sansão', 'active' => '1'),
            array('id' => '366', 'city_id' => '9157', 'name' => 'Rua Natal', 'active' => '1'),
            array('id' => '367', 'city_id' => '6184', 'name' => 'Rua das Larajeiras', 'active' => '1'),
            array('id' => '368', 'city_id' => '9157', 'name' => 'Rua Tocantins', 'active' => '1'),
            array('id' => '370', 'city_id' => '9558', 'name' => 'Av. Mauá', 'active' => '1'),
            array('id' => '371', 'city_id' => '9157', 'name' => 'Av. Rio de Janeiro', 'active' => '1'),
            array('id' => '373', 'city_id' => '8830', 'name' => 'Rua Rondônia', 'active' => '1'),
            array('id' => '374', 'city_id' => '9157', 'name' => 'Rua Jundia', 'active' => '1'),
            array('id' => '375', 'city_id' => '5212', 'name' => 'Av. Minas Gerais', 'active' => '1'),
            array('id' => '376', 'city_id' => '6044', 'name' => 'Rua Ruy Barbosa', 'active' => '1'),
            array('id' => '377', 'city_id' => '9558', 'name' => 'Rua Manoel Dionísio Sobrinho', 'active' => '1'),
            array('id' => '378', 'city_id' => '9157', 'name' => 'Rua Cascudo', 'active' => '1'),
            array('id' => '379', 'city_id' => '8340', 'name' => 'Av. dos Bandeirantes', 'active' => '1'),
            array('id' => '380', 'city_id' => '6184', 'name' => 'Rua dos Antúrios', 'active' => '1'),
            array('id' => '382', 'city_id' => '6184', 'name' => 'Rua dos Mamoeiros', 'active' => '1'),
            array('id' => '384', 'city_id' => '6184', 'name' => 'Rua dos Jatobás', 'active' => '1'),
            array('id' => '385', 'city_id' => '9558', 'name' => 'Av. Brasília', 'active' => '1'),
            array('id' => '386', 'city_id' => '6184', 'name' => 'Rua dos Flamboyants', 'active' => '1'),
            array('id' => '387', 'city_id' => '9558', 'name' => 'Rua José Corsino (Rua 12)', 'active' => '1'),
            array('id' => '388', 'city_id' => '9157', 'name' => 'Rua Minosso', 'active' => '1'),
            array('id' => '390', 'city_id' => '9558', 'name' => 'Rua José Alves de Souza (Rua 18)', 'active' => '1'),
            array('id' => '391', 'city_id' => '9558', 'name' => 'Rua Avelina Jaci Bohn (Rua 2)', 'active' => '1'),
            array('id' => '392', 'city_id' => '6037', 'name' => 'Rua Ari Leite Campos', 'active' => '1'),
            array('id' => '393', 'city_id' => '5212', 'name' => 'Av. Tocantins', 'active' => '1'),
            array('id' => '394', 'city_id' => '9558', 'name' => 'Av. Nilo Torres', 'active' => '1'),
            array('id' => '395', 'city_id' => '9558', 'name' => 'Rua Erotides Padilha', 'active' => '1'),
            array('id' => '396', 'city_id' => '6178', 'name' => 'Rua Magda', 'active' => '1'),
            array('id' => '397', 'city_id' => '936', 'name' => 'Av. Airton Senna', 'active' => '1'),
            array('id' => '398', 'city_id' => '7898', 'name' => 'Rua Cel. Virgínio Ferreira', 'active' => '1'),
            array('id' => '399', 'city_id' => '7898', 'name' => 'Rua Antonio Bruno', 'active' => '1'),
            array('id' => '400', 'city_id' => '9157', 'name' => 'Rua Barbado', 'active' => '1'),
            array('id' => '402', 'city_id' => '936', 'name' => 'Rod. MT 246', 'active' => '1'),
            array('id' => '404', 'city_id' => '9157', 'name' => 'Rua Paraíba', 'active' => '1'),
            array('id' => '405', 'city_id' => '6184', 'name' => 'Rua das Cerejeiras', 'active' => '1'),
            array('id' => '407', 'city_id' => '9157', 'name' => 'Rua Rio Branco', 'active' => '1'),
            array('id' => '408', 'city_id' => '6184', 'name' => 'Rua das Sibipirunas', 'active' => '1'),
            array('id' => '409', 'city_id' => '6184', 'name' => 'Rua das Flores', 'active' => '1'),
            array('id' => '410', 'city_id' => '6184', 'name' => 'Rua dos Tamarindos', 'active' => '1'),
            array('id' => '411', 'city_id' => '8830', 'name' => 'Rua São Francisco', 'active' => '1'),
            array('id' => '414', 'city_id' => '6177', 'name' => 'Av. Blairo Maggi', 'active' => '1'),
            array('id' => '415', 'city_id' => '9157', 'name' => 'Rua do Piapara', 'active' => '1'),
            array('id' => '416', 'city_id' => '9558', 'name' => 'Rua Arlindo Nogueira Gomes (Rua 7A)', 'active' => '1'),
            array('id' => '417', 'city_id' => '9558', 'name' => 'Rua 30 de Julho', 'active' => '1'),
            array('id' => '418', 'city_id' => '7898', 'name' => 'Rua São Benedito', 'active' => '1'),
            array('id' => '422', 'city_id' => '6184', 'name' => 'Rua dos Jambos', 'active' => '1'),
            array('id' => '423', 'city_id' => '8830', 'name' => 'Av. Peru', 'active' => '1'),
            array('id' => '424', 'city_id' => '6184', 'name' => 'Rua das Sete Copas', 'active' => '1'),
            array('id' => '425', 'city_id' => '9157', 'name' => 'Rua São Tomás', 'active' => '1'),
            array('id' => '426', 'city_id' => '936', 'name' => 'Rua Pernambuco', 'active' => '1'),
            array('id' => '427', 'city_id' => '8830', 'name' => 'Av. Chile', 'active' => '1'),
            array('id' => '428', 'city_id' => '9157', 'name' => 'Rua Beija-Flor', 'active' => '1'),
            array('id' => '429', 'city_id' => '6184', 'name' => 'Rua das Rosas', 'active' => '1'),
            array('id' => '430', 'city_id' => '9157', 'name' => 'Rua Traíra', 'active' => '1'),
            array('id' => '431', 'city_id' => '6184', 'name' => 'Rua das Sapucaias', 'active' => '1'),
            array('id' => '433', 'city_id' => '2962', 'name' => 'Rua Francisco Gaspar', 'active' => '1'),
            array('id' => '435', 'city_id' => '9157', 'name' => 'Av. Pirambóia', 'active' => '1'),
            array('id' => '438', 'city_id' => '2962', 'name' => 'Terminal Rodoviário Posto Gil', 'active' => '1'),
            array('id' => '439', 'city_id' => '936', 'name' => 'Praça Ângelo Masson', 'active' => '1'),
            array('id' => '441', 'city_id' => '9157', 'name' => 'Av. Rotary Internacional', 'active' => '1'),
            array('id' => '442', 'city_id' => '9157', 'name' => 'Rod. MT 235', 'active' => '1'),
            array('id' => '446', 'city_id' => '9157', 'name' => 'Av. Engenheiro José da Silva Tiago', 'active' => '1'),
            array('id' => '447', 'city_id' => '647', 'name' => 'Av. Sesquicentenário', 'active' => '1'),
            array('id' => '448', 'city_id' => '936', 'name' => 'Av. Julio Miranda', 'active' => '1'),
            array('id' => '450', 'city_id' => '6184', 'name' => 'Av. das Gaivotas', 'active' => '1'),
            array('id' => '451', 'city_id' => '6184', 'name' => 'Rua das Itaúbas', 'active' => '1'),
            array('id' => '452', 'city_id' => '9157', 'name' => 'Rua Roberto Carlos Brolio', 'active' => '1'),
            array('id' => '453', 'city_id' => '6044', 'name' => 'Rua Bráz Alves da Costa', 'active' => '1'),
            array('id' => '454', 'city_id' => '9558', 'name' => 'Rua Janeiro', 'active' => '1'),
            array('id' => '455', 'city_id' => '2962', 'name' => 'Rua dos Sindicatos', 'active' => '1'),
            array('id' => '456', 'city_id' => '9558', 'name' => 'Rua Domingos Germano de Souza (Rua 5A)', 'active' => '1'),
            array('id' => '458', 'city_id' => '6184', 'name' => 'Rua das Mangabas', 'active' => '1'),
            array('id' => '459', 'city_id' => '936', 'name' => 'Av. Emanoel Pinheiro', 'active' => '1'),
            array('id' => '460', 'city_id' => '6184', 'name' => 'Rua dos Lírios', 'active' => '1'),
            array('id' => '462', 'city_id' => '9558', 'name' => 'Rua Concorde', 'active' => '1'),
            array('id' => '463', 'city_id' => '9157', 'name' => 'Rua dos Girassóis', 'active' => '1'),
            array('id' => '464', 'city_id' => '936', 'name' => 'Rua Josino Prado', 'active' => '1'),
            array('id' => '465', 'city_id' => '936', 'name' => 'Rua Voluntários da Pátria', 'active' => '1'),
            array('id' => '466', 'city_id' => '9157', 'name' => 'Rua Martinho Lutero', 'active' => '1'),
            array('id' => '469', 'city_id' => '2962', 'name' => 'Rua das Acácias', 'active' => '1'),
            array('id' => '470', 'city_id' => '2962', 'name' => 'Rua Projetada', 'active' => '1'),
            array('id' => '471', 'city_id' => '6184', 'name' => 'Rua dos Amapás', 'active' => '1'),
            array('id' => '472', 'city_id' => '6184', 'name' => 'Rua dos Tuiuiús', 'active' => '1'),
            array('id' => '474', 'city_id' => '6177', 'name' => 'Rua Minas Gerais', 'active' => '1'),
            array('id' => '475', 'city_id' => '6184', 'name' => 'Rua das Tulipas', 'active' => '1'),
            array('id' => '476', 'city_id' => '6184', 'name' => 'Rua das Mangueiras', 'active' => '1'),
            array('id' => '477', 'city_id' => '2932', 'name' => 'Rua Jovenal Domingos', 'active' => '1'),
            array('id' => '478', 'city_id' => '8830', 'name' => 'Rua Nobres', 'active' => '1'),
            array('id' => '479', 'city_id' => '6184', 'name' => 'Rua dos Tamareiros', 'active' => '1'),
            array('id' => '480', 'city_id' => '8340', 'name' => 'Rua Padre Josá Anchieta', 'active' => '1'),
            array('id' => '482', 'city_id' => '8830', 'name' => 'Rua São Jorge', 'active' => '1'),
            array('id' => '484', 'city_id' => '647', 'name' => 'Rua Glicério Martins Pinto', 'active' => '1'),
            array('id' => '485', 'city_id' => '647', 'name' => 'Rua Messias Cassemiro Barbosa', 'active' => '1'),
            array('id' => '487', 'city_id' => '6037', 'name' => 'Praça Roosevelt Rachid Jaudy', 'active' => '1'),
            array('id' => '489', 'city_id' => '2962', 'name' => 'Rua Catarina', 'active' => '1'),
            array('id' => '490', 'city_id' => '6044', 'name' => 'Rua Major Simão Aureliano Barros', 'active' => '1'),
            array('id' => '491', 'city_id' => '6037', 'name' => 'Rua Pofª Niva Matos de Oliveira', 'active' => '1'),
            array('id' => '492', 'city_id' => '6184', 'name' => 'Rua dos Angelins', 'active' => '1'),
            array('id' => '493', 'city_id' => '6037', 'name' => 'Av. 1 Maio', 'active' => '1'),
            array('id' => '494', 'city_id' => '6044', 'name' => 'Rua Ademar Barros', 'active' => '1'),
            array('id' => '495', 'city_id' => '2962', 'name' => 'Rua Pitombeiras', 'active' => '1'),
            array('id' => '496', 'city_id' => '7898', 'name' => 'Av. Jorge José Zamar', 'active' => '1'),
            array('id' => '497', 'city_id' => '6177', 'name' => 'Rua Casa Leai', 'active' => '1'),
            array('id' => '498', 'city_id' => '6037', 'name' => 'Rua Niva Matos de Oliveira', 'active' => '1'),
            array('id' => '499', 'city_id' => '6184', 'name' => 'Av. das Garças', 'active' => '1'),
            array('id' => '501', 'city_id' => '2932', 'name' => 'Rua António Alves Teixeira', 'active' => '1'),
            array('id' => '502', 'city_id' => '6184', 'name' => 'Rua das Açucenas', 'active' => '1'),
            array('id' => '503', 'city_id' => '6184', 'name' => 'Rua das Copaibas', 'active' => '1'),
            array('id' => '504', 'city_id' => '6178', 'name' => 'Rua Fabiana', 'active' => '1'),
            array('id' => '505', 'city_id' => '7898', 'name' => 'Rua João Pessoa', 'active' => '1'),
            array('id' => '506', 'city_id' => '2962', 'name' => 'Rua das Paineiras', 'active' => '1'),
            array('id' => '507', 'city_id' => '7898', 'name' => 'Rua Luiz de Matos', 'active' => '1'),
            array('id' => '510', 'city_id' => '8340', 'name' => 'Rua Coronel Virgínio Ferreira de Almeida', 'active' => '1'),
            array('id' => '512', 'city_id' => '7898', 'name' => 'Rua Pedro Correia', 'active' => '1'),
            array('id' => '515', 'city_id' => '6184', 'name' => 'Rua dos Buritis', 'active' => '1'),
            array('id' => '516', 'city_id' => '6184', 'name' => 'Rua dos Angicos', 'active' => '1'),
            array('id' => '517', 'city_id' => '6184', 'name' => 'Av. dos Jacarandás', 'active' => '1'),
            array('id' => '520', 'city_id' => '2932', 'name' => 'Rua Tapira', 'active' => '1'),
            array('id' => '523', 'city_id' => '6184', 'name' => 'Rua das Acerolas', 'active' => '1'),
            array('id' => '524', 'city_id' => '647', 'name' => 'Rua Oscar Josset', 'active' => '1'),
            array('id' => '525', 'city_id' => '647', 'name' => 'Rua Jânio Quadros', 'active' => '1'),
            array('id' => '526', 'city_id' => '6184', 'name' => 'Rua dos Alecrins', 'active' => '1'),
            array('id' => '529', 'city_id' => '6037', 'name' => 'Rua Trankindo', 'active' => '1'),
            array('id' => '530', 'city_id' => '6044', 'name' => 'Rua Antônio Olimpio de Oliveira', 'active' => '1'),
            array('id' => '531', 'city_id' => '6184', 'name' => 'Rua das Canelas', 'active' => '1'),
            array('id' => '532', 'city_id' => '6184', 'name' => 'Rua das Jaboticabeiras', 'active' => '1'),
            array('id' => '533', 'city_id' => '2932', 'name' => 'Rua Presidente Costa e Silva', 'active' => '1'),
            array('id' => '534', 'city_id' => '6184', 'name' => 'Rua das Goiaberas', 'active' => '1'),
            array('id' => '535', 'city_id' => '6184', 'name' => 'Rua dos Pavões', 'active' => '1'),
            array('id' => '536', 'city_id' => '6184', 'name' => 'Rua das Sucupiras', 'active' => '1'),
            array('id' => '537', 'city_id' => '6184', 'name' => 'Rua das Amoras', 'active' => '1'),
            array('id' => '538', 'city_id' => '6184', 'name' => 'Av. das Perdizes', 'active' => '1'),
            array('id' => '539', 'city_id' => '647', 'name' => 'Rua Getúlio Vargas', 'active' => '1'),
            array('id' => '540', 'city_id' => '7898', 'name' => 'Rua Presidente Vargas', 'active' => '1'),
            array('id' => '541', 'city_id' => '6037', 'name' => 'Rua Goiás', 'active' => '1'),
            array('id' => '542', 'city_id' => '8830', 'name' => 'Rua Maranhão', 'active' => '1'),
            array('id' => '544', 'city_id' => '8830', 'name' => 'Rua Paraná', 'active' => '1'),
            array('id' => '545', 'city_id' => '6044', 'name' => 'Av. Wellington Fagundes', 'active' => '1'),
            array('id' => '546', 'city_id' => '7898', 'name' => 'Rua Dom Orlando Chaves', 'active' => '1'),
            array('id' => '547', 'city_id' => '6184', 'name' => 'Rua Circular', 'active' => '1'),
            array('id' => '548', 'city_id' => '6178', 'name' => 'Av. Santana', 'active' => '1'),
            array('id' => '549', 'city_id' => '2962', 'name' => 'Praça Bairro da Ponte', 'active' => '1'),
            array('id' => '550', 'city_id' => '647', 'name' => 'Rua Joel dos Santos', 'active' => '1'),
            array('id' => '551', 'city_id' => '6177', 'name' => 'Rua das Dálias', 'active' => '1'),
            array('id' => '552', 'city_id' => '2932', 'name' => 'Rua Vitória', 'active' => '1'),
            array('id' => '553', 'city_id' => '6184', 'name' => 'Rua Meri Luise', 'active' => '1'),
            array('id' => '554', 'city_id' => '6184', 'name' => 'Rua das Mineiras', 'active' => '1'),
            array('id' => '555', 'city_id' => '2962', 'name' => 'Trav. dos Parecis', 'active' => '1'),
            array('id' => '557', 'city_id' => '2962', 'name' => 'Rua Urbano Rodrigues Fontes', 'active' => '1'),
            array('id' => '558', 'city_id' => '6037', 'name' => 'Rua Tenente Laurindo Moreira', 'active' => '1'),
            array('id' => '561', 'city_id' => '8830', 'name' => 'Rod. MT 010', 'active' => '1'),
            array('id' => '562', 'city_id' => '8830', 'name' => 'Rua João Quintino', 'active' => '1'),
            array('id' => '564', 'city_id' => '2932', 'name' => 'Av. João Pessoa', 'active' => '1'),
            array('id' => '565', 'city_id' => '6037', 'name' => 'Av. Marzagão', 'active' => '1'),
            array('id' => '566', 'city_id' => '6178', 'name' => 'Rua Tatiane', 'active' => '1'),
            array('id' => '567', 'city_id' => '6184', 'name' => 'Rua das Mamonas', 'active' => '1'),
            array('id' => '568', 'city_id' => '6044', 'name' => 'Rua Pedro Araújo Ramos', 'active' => '1'),
            array('id' => '569', 'city_id' => '6184', 'name' => 'Rua das Alfazemas', 'active' => '1'),
            array('id' => '570', 'city_id' => '6184', 'name' => 'Rod. MT 249', 'active' => '1'),
            array('id' => '571', 'city_id' => '7898', 'name' => 'Rua Nossa Senhora Aparecida', 'active' => '1'),
            array('id' => '572', 'city_id' => '2962', 'name' => 'Rua Marcílio Freire Régis', 'active' => '1'),
            array('id' => '573', 'city_id' => '6184', 'name' => 'Estrada POS', 'active' => '1'),
            array('id' => '575', 'city_id' => '6037', 'name' => 'Rua Maurício Sampaio', 'active' => '1'),
            array('id' => '576', 'city_id' => '6044', 'name' => 'Rua Brg. Eduardo Gomes', 'active' => '1'),
            array('id' => '578', 'city_id' => '8830', 'name' => 'Av. Bria Norte', 'active' => '1'),
            array('id' => '579', 'city_id' => '6177', 'name' => 'Av. André Maggi', 'active' => '1'),
            array('id' => '580', 'city_id' => '647', 'name' => 'Rua Frederico Garcez', 'active' => '1'),
            array('id' => '581', 'city_id' => '2962', 'name' => 'Rua Niterói', 'active' => '1'),
            array('id' => '582', 'city_id' => '8340', 'name' => 'Rua do Comércio', 'active' => '1'),
            array('id' => '584', 'city_id' => '6037', 'name' => 'Rua Valdon Varjão', 'active' => '1'),
            array('id' => '585', 'city_id' => '6184', 'name' => 'Rua das Gravatas', 'active' => '1'),
            array('id' => '587', 'city_id' => '6184', 'name' => 'Rua dos Coqueiros', 'active' => '1'),
            array('id' => '588', 'city_id' => '2962', 'name' => 'Rua Alexandrina Ribeiro Dallagnol', 'active' => '1'),
            array('id' => '589', 'city_id' => '6184', 'name' => 'Parque de Exposições', 'active' => '1'),
            array('id' => '590', 'city_id' => '8830', 'name' => 'Rua São Pedro', 'active' => '1'),
            array('id' => '591', 'city_id' => '6184', 'name' => 'Terminal Rodoviário', 'active' => '1'),
            array('id' => '592', 'city_id' => '6044', 'name' => 'Rua Cuiabá', 'active' => '1'),
            array('id' => '593', 'city_id' => '6037', 'name' => 'Av. Principal', 'active' => '1'),
            array('id' => '594', 'city_id' => '6044', 'name' => 'Estrada Santaninha', 'active' => '1'),
            array('id' => '595', 'city_id' => '6184', 'name' => 'Viveiro Municipal', 'active' => '1'),
            array('id' => '596', 'city_id' => '6184', 'name' => 'Rua das Herbênias', 'active' => '1'),
            array('id' => '597', 'city_id' => '647', 'name' => 'Rua Presidente Dutra', 'active' => '1'),
            array('id' => '599', 'city_id' => '6037', 'name' => 'Rua Corumbá', 'active' => '1'),
            array('id' => '600', 'city_id' => '6037', 'name' => 'Rua Porto Público', 'active' => '1'),
            array('id' => '601', 'city_id' => '8830', 'name' => 'Rua Alberto Ricardo Buss', 'active' => '1'),
            array('id' => '602', 'city_id' => '8830', 'name' => 'Rua Rio de Janeiro', 'active' => '1'),
            array('id' => '603', 'city_id' => '6184', 'name' => 'Posto Santa Rita', 'active' => '1'),
            array('id' => '604', 'city_id' => '7898', 'name' => 'Rua Coronel Botelho', 'active' => '1'),
            array('id' => '605', 'city_id' => '6184', 'name' => 'Rua dos Piquizeiros', 'active' => '1'),
            array('id' => '606', 'city_id' => '2962', 'name' => 'Rua Atílio Visnardi', 'active' => '1'),
            array('id' => '607', 'city_id' => '6184', 'name' => 'Rua das Araucárias', 'active' => '1'),
            array('id' => '608', 'city_id' => '6184', 'name' => 'Rua das Jacutingas', 'active' => '1'),
            array('id' => '609', 'city_id' => '6184', 'name' => 'Rua dos Girassóis', 'active' => '1'),
            array('id' => '610', 'city_id' => '6044', 'name' => 'Rua Duque de Caxias', 'active' => '1'),
            array('id' => '613', 'city_id' => '7898', 'name' => 'Av. Coronel Duarte', 'active' => '1'),
            array('id' => '614', 'city_id' => '2962', 'name' => 'Rua Presidente Prudente', 'active' => '1'),
            array('id' => '615', 'city_id' => '2932', 'name' => 'Rua Presidente Castelo Branco', 'active' => '1'),
            array('id' => '616', 'city_id' => '2932', 'name' => 'Rua Juscelino Kubitschek', 'active' => '1'),
            array('id' => '617', 'city_id' => '8830', 'name' => 'Rua Londrina', 'active' => '1'),
            array('id' => '618', 'city_id' => '936', 'name' => 'Rua Santa Cruz', 'active' => '1'),
            array('id' => '619', 'city_id' => '9558', 'name' => 'Av. Castanheiras', 'active' => '1'),
            array('id' => '620', 'city_id' => '9558', 'name' => 'Rua Euclides Geraldo Medeiros (Rua 13)', 'active' => '1'),
            array('id' => '621', 'city_id' => '6037', 'name' => 'Rua Santiago', 'active' => '1'),
            array('id' => '622', 'city_id' => '8830', 'name' => 'Rua Sergipe', 'active' => '1'),
            array('id' => '624', 'city_id' => '8340', 'name' => 'Rua Papa João XXIII', 'active' => '1'),
            array('id' => '626', 'city_id' => '9558', 'name' => 'Rua Nespits de Carvalho (Rua 19)', 'active' => '1'),
            array('id' => '627', 'city_id' => '9157', 'name' => 'Av. Getúlio Vargas', 'active' => '1'),
            array('id' => '629', 'city_id' => '9558', 'name' => 'Rua José Mariano (15A)', 'active' => '1'),
            array('id' => '630', 'city_id' => '9157', 'name' => 'Rua dos Lírios', 'active' => '1'),
            array('id' => '631', 'city_id' => '9157', 'name' => 'Rua Piaba', 'active' => '1'),
            array('id' => '633', 'city_id' => '9558', 'name' => 'Rod. MT 358', 'active' => '1'),
            array('id' => '635', 'city_id' => '9558', 'name' => 'Rua Arlindo Lopes da Silva (Rua 3)', 'active' => '1'),
            array('id' => '636', 'city_id' => '9157', 'name' => 'Rua Terezina', 'active' => '1'),
            array('id' => '637', 'city_id' => '9558', 'name' => 'Rua Cisne', 'active' => '1'),
            array('id' => '638', 'city_id' => '9157', 'name' => 'Rua Amazonas', 'active' => '1'),
            array('id' => '639', 'city_id' => '9558', 'name' => 'Av. Amoreiras', 'active' => '1'),
            array('id' => '640', 'city_id' => '5212', 'name' => 'Av. Bahia', 'active' => '1'),
            array('id' => '641', 'city_id' => '9558', 'name' => 'Av. Vitória', 'active' => '1'),
            array('id' => '643', 'city_id' => '5212', 'name' => 'Av. Pernambuco', 'active' => '1'),
            array('id' => '644', 'city_id' => '936', 'name' => 'Av. Santa Catarina', 'active' => '1'),
            array('id' => '646', 'city_id' => '9558', 'name' => 'Rua Francisco F. Ramos (Rua 20)', 'active' => '1'),
            array('id' => '648', 'city_id' => '9157', 'name' => 'Rua Princesa Isabel', 'active' => '1'),
            array('id' => '650', 'city_id' => '9157', 'name' => 'Av. Corimba', 'active' => '1'),
            array('id' => '651', 'city_id' => '9157', 'name' => 'Rua Belém', 'active' => '1'),
            array('id' => '652', 'city_id' => '9157', 'name' => 'Av. Senhor Atílio Fontana', 'active' => '1'),
            array('id' => '653', 'city_id' => '9558', 'name' => 'Rua Ariovaldo Stela', 'active' => '1'),
            array('id' => '656', 'city_id' => '9558', 'name' => 'Av. Curitiba', 'active' => '1'),
            array('id' => '658', 'city_id' => '936', 'name' => 'Av. Macedo', 'active' => '1'),
            array('id' => '659', 'city_id' => '9558', 'name' => 'Rod. MT 258', 'active' => '1'),
            array('id' => '661', 'city_id' => '9451', 'name' => 'Rua Bene', 'active' => '1'),
            array('id' => '662', 'city_id' => '9157', 'name' => 'Rua Do Matrinchã', 'active' => '1'),
            array('id' => '663', 'city_id' => '9157', 'name' => 'Rua das Violetas', 'active' => '1'),
            array('id' => '664', 'city_id' => '936', 'name' => 'Av. Nações', 'active' => '1'),
            array('id' => '665', 'city_id' => '9157', 'name' => 'Av. Ceará', 'active' => '1'),
            array('id' => '666', 'city_id' => '9558', 'name' => 'Rua Evilin Crestani', 'active' => '1'),
            array('id' => '667', 'city_id' => '9558', 'name' => 'Rua Alziro Zarur', 'active' => '1'),
            array('id' => '669', 'city_id' => '936', 'name' => 'Rua Bela Vista', 'active' => '1'),
            array('id' => '671', 'city_id' => '9157', 'name' => 'Rua Violetas', 'active' => '1'),
            array('id' => '673', 'city_id' => '9558', 'name' => 'Rua São João', 'active' => '1'),
            array('id' => '676', 'city_id' => '9157', 'name' => 'Rua Boa Esperança', 'active' => '1'),
            array('id' => '677', 'city_id' => '2962', 'name' => 'Estrada Rio Preto', 'active' => '1'),
            array('id' => '678', 'city_id' => '9558', 'name' => 'Rua Tapirapuã', 'active' => '1'),
            array('id' => '679', 'city_id' => '2962', 'name' => 'Rua João Paulo II', 'active' => '1'),
            array('id' => '681', 'city_id' => '9558', 'name' => 'Rua Delcio Buralli (Rua 22)', 'active' => '1'),
            array('id' => '682', 'city_id' => '9451', 'name' => 'Av. Marginal Esquerda', 'active' => '1'),
            array('id' => '684', 'city_id' => '936', 'name' => 'Rua Rio Negro', 'active' => '1'),
            array('id' => '685', 'city_id' => '9451', 'name' => 'Rod. MT 404', 'active' => '1'),
            array('id' => '686', 'city_id' => '9558', 'name' => 'Estrada dos Coqueiros', 'active' => '1'),
            array('id' => '687', 'city_id' => '9558', 'name' => 'Rua Costa', 'active' => '1'),
            array('id' => '689', 'city_id' => '936', 'name' => 'Rua Antônio Félix Nascimento', 'active' => '1'),
            array('id' => '690', 'city_id' => '9558', 'name' => 'Av. Beija-Flor', 'active' => '1'),
            array('id' => '691', 'city_id' => '9558', 'name' => 'Rua Macedo', 'active' => '1'),
            array('id' => '692', 'city_id' => '9558', 'name' => 'Rua Antonio Ribeiro da Rocha (9A)', 'active' => '1'),
            array('id' => '694', 'city_id' => '9157', 'name' => 'Rua Porto Alegre', 'active' => '1'),
            array('id' => '695', 'city_id' => '9157', 'name' => 'Av. Trabalhadores', 'active' => '1'),
            array('id' => '696', 'city_id' => '9157', 'name' => 'Rua 19 de Setembro', 'active' => '1'),
            array('id' => '697', 'city_id' => '936', 'name' => 'Distrito Industrial', 'active' => '1'),
            array('id' => '700', 'city_id' => '9558', 'name' => 'Rua Osvaldo Pereira de Araújo', 'active' => '1'),
            array('id' => '701', 'city_id' => '9558', 'name' => 'Rua Ramon Sanches Marques', 'active' => '1'),
            array('id' => '704', 'city_id' => '936', 'name' => 'Av. Goiás', 'active' => '1'),
            array('id' => '706', 'city_id' => '936', 'name' => 'Rua São Sebastião', 'active' => '1'),
            array('id' => '708', 'city_id' => '936', 'name' => 'Av. Paiaguás', 'active' => '1'),
            array('id' => '709', 'city_id' => '9157', 'name' => 'Rua Tito Olívio', 'active' => '1'),
            array('id' => '710', 'city_id' => '9558', 'name' => 'Av. Almirante Barroso', 'active' => '1'),
            array('id' => '713', 'city_id' => '9451', 'name' => 'Rua Mário Quintana', 'active' => '1'),
            array('id' => '714', 'city_id' => '9157', 'name' => 'Rua Sucupira', 'active' => '1'),
            array('id' => '715', 'city_id' => '9558', 'name' => 'Rua José Porfino', 'active' => '1'),
            array('id' => '716', 'city_id' => '9157', 'name' => 'Av. David Mufatto', 'active' => '1'),
            array('id' => '717', 'city_id' => '9451', 'name' => 'Rua São José', 'active' => '1'),
            array('id' => '718', 'city_id' => '9157', 'name' => 'Rua Rodolfo Ulrich', 'active' => '1'),
            array('id' => '719', 'city_id' => '936', 'name' => 'Rua Frederico Josett', 'active' => '1'),
            array('id' => '721', 'city_id' => '9157', 'name' => 'Av. do Boto', 'active' => '1'),
            array('id' => '722', 'city_id' => '936', 'name' => 'Av. Pelachin', 'active' => '1'),
            array('id' => '723', 'city_id' => '9157', 'name' => 'Rua Porto Velho', 'active' => '1'),
            array('id' => '724', 'city_id' => '9558', 'name' => 'Av. das Cerejeiras', 'active' => '1'),
            array('id' => '726', 'city_id' => '9157', 'name' => 'Rua Bagre', 'active' => '1'),
            array('id' => '729', 'city_id' => '936', 'name' => 'Av. Xavantes', 'active' => '1'),
            array('id' => '730', 'city_id' => '936', 'name' => 'Rua Rio Preto', 'active' => '1'),
            array('id' => '731', 'city_id' => '9157', 'name' => 'Av. Palmeiras', 'active' => '1'),
            array('id' => '732', 'city_id' => '9157', 'name' => 'Rua Cambará', 'active' => '1'),
            array('id' => '734', 'city_id' => '9558', 'name' => 'Av. Carlos Taiano', 'active' => '1'),
            array('id' => '735', 'city_id' => '9558', 'name' => 'Rua Rotary Internacional (Rua 3A)', 'active' => '1'),
            array('id' => '736', 'city_id' => '9157', 'name' => 'Rua Piauí', 'active' => '1'),
            array('id' => '737', 'city_id' => '6184', 'name' => 'Rua das Carambolas', 'active' => '1'),
            array('id' => '738', 'city_id' => '9558', 'name' => 'Rua José Duarte', 'active' => '1'),
            array('id' => '746', 'city_id' => '6187', 'name' => 'Av. Governador Carlos Bezerra', 'active' => '1'),
            array('id' => '747', 'city_id' => '9558', 'name' => 'Av. Perimetral', 'active' => '1'),
            array('id' => '748', 'city_id' => '6187', 'name' => 'Rod. Governador Fernando Correa da Costa', 'active' => '1'),
            array('id' => '749', 'city_id' => '9157', 'name' => 'Praça das Antenas', 'active' => '1'),
            array('id' => '751', 'city_id' => '9558', 'name' => 'Rua Floresta', 'active' => '1'),
            array('id' => '752', 'city_id' => '9558', 'name' => 'Estrada da Reserva', 'active' => '1'),
            array('id' => '753', 'city_id' => '9558', 'name' => 'Rua José Flauzino de Oliveira', 'active' => '1'),
            array('id' => '754', 'city_id' => '9558', 'name' => 'Rua Vilibaldo Behling', 'active' => '1'),
            array('id' => '755', 'city_id' => '9558', 'name' => 'Rua Valdemar da Cruz', 'active' => '1'),
            array('id' => '756', 'city_id' => '6187', 'name' => 'Av. Pedro Pedrossian', 'active' => '1'),
            array('id' => '758', 'city_id' => '9558', 'name' => 'Rua Dona Amélia', 'active' => '1'),
            array('id' => '759', 'city_id' => '9558', 'name' => 'Rua Antonio Batista Costa (Rua 17)', 'active' => '1'),
            array('id' => '761', 'city_id' => '9558', 'name' => 'Rua Luiz Martins Cardoso', 'active' => '1'),
            array('id' => '762', 'city_id' => '9558', 'name' => 'Rua Antonio José da Silva', 'active' => '1'),
            array('id' => '764', 'city_id' => '9558', 'name' => 'Av. Campo Grande', 'active' => '1'),
            array('id' => '765', 'city_id' => '2962', 'name' => 'Rua São Silvestre', 'active' => '1'),
            array('id' => '771', 'city_id' => '936', 'name' => 'Rua Rouxinol', 'active' => '1'),
            array('id' => '773', 'city_id' => '936', 'name' => 'Av. Elídia Oliveira Carneiro', 'active' => '1'),
            array('id' => '774', 'city_id' => '936', 'name' => 'Rua Carajás', 'active' => '1'),
            array('id' => '775', 'city_id' => '936', 'name' => 'Rua João Custódio Silva', 'active' => '1'),
            array('id' => '777', 'city_id' => '936', 'name' => 'Rua da Alegria', 'active' => '1'),
            array('id' => '778', 'city_id' => '936', 'name' => 'Rua Ricardo Guedes Silva', 'active' => '1'),
            array('id' => '780', 'city_id' => '936', 'name' => 'Rua José Antônio de Farias', 'active' => '1'),
            array('id' => '782', 'city_id' => '936', 'name' => 'Av. Planalto', 'active' => '1'),
            array('id' => '783', 'city_id' => '936', 'name' => 'Rua João de Campos Borges', 'active' => '1'),
            array('id' => '784', 'city_id' => '936', 'name' => 'Rua 31 de Março', 'active' => '1'),
            array('id' => '785', 'city_id' => '936', 'name' => 'Av. Pedro de Campos Borges', 'active' => '1'),
            array('id' => '786', 'city_id' => '936', 'name' => 'Rod. MT 247', 'active' => '1'),
            array('id' => '788', 'city_id' => '936', 'name' => 'Av. Josefina Rocha Macedo', 'active' => '1'),
            array('id' => '789', 'city_id' => '2962', 'name' => 'Rua Petrolina', 'active' => '1'),
            array('id' => '790', 'city_id' => '9157', 'name' => 'Rua Severino Eufrasino Lima', 'active' => '1'),
            array('id' => '791', 'city_id' => '2962', 'name' => 'Rua Arapongas', 'active' => '1'),
            array('id' => '792', 'city_id' => '2962', 'name' => 'Rua Jatobá', 'active' => '1'),
            array('id' => '794', 'city_id' => '647', 'name' => 'Rua Pacoval', 'active' => '1'),
            array('id' => '795', 'city_id' => '2962', 'name' => 'Rua Timbaúva', 'active' => '1'),
            array('id' => '797', 'city_id' => '936', 'name' => 'Av. Joaquim Mariano Miranda', 'active' => '1'),
            array('id' => '799', 'city_id' => '936', 'name' => 'Rua Goitacazes', 'active' => '1'),
            array('id' => '800', 'city_id' => '936', 'name' => 'Rua Beija Flor', 'active' => '1'),
            array('id' => '801', 'city_id' => '936', 'name' => 'Rua Tabatinga', 'active' => '1'),
            array('id' => '802', 'city_id' => '6187', 'name' => 'Rua Costa e Silva', 'active' => '1'),
            array('id' => '804', 'city_id' => '6187', 'name' => 'Rua João Gregório da Silva', 'active' => '1'),
            array('id' => '807', 'city_id' => '936', 'name' => 'Av. Manaus', 'active' => '1'),
            array('id' => '808', 'city_id' => '936', 'name' => 'Rua Basílio Alberto Zandonardi', 'active' => '1'),
            array('id' => '810', 'city_id' => '6187', 'name' => 'Rua Guatemala', 'active' => '1'),
            array('id' => '811', 'city_id' => '6187', 'name' => 'Rua Wilson Almeida', 'active' => '1'),
            array('id' => '812', 'city_id' => '936', 'name' => 'Rua Manoel Rodrigues', 'active' => '1'),
            array('id' => '813', 'city_id' => '6187', 'name' => 'Rua Colômbia', 'active' => '1'),
            array('id' => '814', 'city_id' => '6187', 'name' => 'Rua dos Ipês', 'active' => '1'),
            array('id' => '815', 'city_id' => '6184', 'name' => 'Rua dos Cambarás', 'active' => '1'),
            array('id' => '818', 'city_id' => '2962', 'name' => 'Rua Progresso', 'active' => '1'),
            array('id' => '824', 'city_id' => '6187', 'name' => 'Rua José Alves Leão', 'active' => '1'),
            array('id' => '825', 'city_id' => '2962', 'name' => 'Estrada do Caramba', 'active' => '1'),
            array('id' => '826', 'city_id' => '6187', 'name' => 'Av. Olacir de Moraes', 'active' => '1'),
            array('id' => '827', 'city_id' => '6187', 'name' => 'Rua Santos Dumont', 'active' => '1'),
            array('id' => '829', 'city_id' => '6187', 'name' => 'Rua Santa Maria', 'active' => '1'),
            array('id' => '830', 'city_id' => '6187', 'name' => 'Rua Sebastião André de Souza', 'active' => '1'),
            array('id' => '831', 'city_id' => '6187', 'name' => 'Rua Panamá', 'active' => '1'),
            array('id' => '832', 'city_id' => '6187', 'name' => 'Av. Presidente Castelo Branco', 'active' => '1'),
            array('id' => '833', 'city_id' => '5212', 'name' => 'Av. Mato Grosso do Sul', 'active' => '1'),
            array('id' => '834', 'city_id' => '6187', 'name' => 'Rua Maria Isabel de Jesus', 'active' => '1'),
            array('id' => '836', 'city_id' => '6187', 'name' => 'Rua 15 de Setembro', 'active' => '1'),
            array('id' => '837', 'city_id' => '6187', 'name' => 'Rua Marcos Freire', 'active' => '1'),
            array('id' => '839', 'city_id' => '6187', 'name' => 'Rua Francisco de Moraes', 'active' => '1'),
            array('id' => '844', 'city_id' => '8830', 'name' => 'Rua Emílio A. Ricardo Buss', 'active' => '1'),
            array('id' => '845', 'city_id' => '2962', 'name' => 'Rua Ji Paraná', 'active' => '1'),
            array('id' => '846', 'city_id' => '2962', 'name' => 'Rua 10', 'active' => '1'),
            array('id' => '847', 'city_id' => '9451', 'name' => 'Rua Otávio de Souza Cruz', 'active' => '1'),
            array('id' => '848', 'city_id' => '5212', 'name' => 'Rua Três de Maio', 'active' => '1'),
            array('id' => '849', 'city_id' => '2962', 'name' => 'Rua M', 'active' => '1'),
            array('id' => '850', 'city_id' => '936', 'name' => 'Av. Tropical', 'active' => '1'),
            array('id' => '851', 'city_id' => '936', 'name' => 'Rua Fonseca Natalino Ribeiro', 'active' => '1'),
            array('id' => '852', 'city_id' => '936', 'name' => 'Rua Marari', 'active' => '1'),
            array('id' => '853', 'city_id' => '2962', 'name' => 'Rua Francisco Ferreira Mendes', 'active' => '1'),
            array('id' => '854', 'city_id' => '647', 'name' => 'Av. Presidente Dutra', 'active' => '1'),
            array('id' => '856', 'city_id' => '2962', 'name' => 'Rua Imperatriz', 'active' => '1'),
            array('id' => '857', 'city_id' => '2962', 'name' => 'Rua Marcelino Juvenil', 'active' => '1'),
            array('id' => '858', 'city_id' => '2962', 'name' => 'Rua 1', 'active' => '1'),
            array('id' => '859', 'city_id' => '8340', 'name' => 'Praça Marechal Rondon', 'active' => '1'),
            array('id' => '860', 'city_id' => '647', 'name' => 'Trav. Alagoas', 'active' => '1'),
            array('id' => '861', 'city_id' => '9558', 'name' => 'Rua 28', 'active' => '1'),
            array('id' => '862', 'city_id' => '9558', 'name' => 'Rod. Anel Viário', 'active' => '1'),
            array('id' => '863', 'city_id' => '2962', 'name' => 'Rua Chapori', 'active' => '1'),
            array('id' => '865', 'city_id' => '647', 'name' => 'Rod. Senador Roberto Campos', 'active' => '1'),
            array('id' => '867', 'city_id' => '9558', 'name' => 'Rua 20', 'active' => '1'),
            array('id' => '868', 'city_id' => '2962', 'name' => 'Rua Dirceu Vieira de Barros', 'active' => '1'),
            array('id' => '869', 'city_id' => '647', 'name' => 'Rua Lauro Salgado Caldeira', 'active' => '1'),
            array('id' => '870', 'city_id' => '9558', 'name' => 'Rua 24', 'active' => '1'),
            array('id' => '871', 'city_id' => '6184', 'name' => 'Av. dos Pavões', 'active' => '1'),
            array('id' => '872', 'city_id' => '6184', 'name' => 'Rua das Ceringueiras', 'active' => '1'),
            array('id' => '873', 'city_id' => '6037', 'name' => 'Rua Prof. Nazaré Balbino da Rocha', 'active' => '1'),
            array('id' => '876', 'city_id' => '9558', 'name' => 'Rua 23', 'active' => '1'),
            array('id' => '877', 'city_id' => '2962', 'name' => 'Rua Buriti', 'active' => '1'),
            array('id' => '879', 'city_id' => '2962', 'name' => 'Rua Tancredo Neves', 'active' => '1'),
            array('id' => '882', 'city_id' => '2962', 'name' => 'Rua Camboatã', 'active' => '1'),
            array('id' => '883', 'city_id' => '2962', 'name' => 'Rua Cajarana', 'active' => '1'),
            array('id' => '884', 'city_id' => '9558', 'name' => 'Rua 6', 'active' => '1'),
            array('id' => '886', 'city_id' => '2962', 'name' => 'Rua Babaçú', 'active' => '1'),
            array('id' => '890', 'city_id' => '9558', 'name' => 'Rua Antonio Barbeiro Herreiro (13-A)', 'active' => '1'),
            array('id' => '892', 'city_id' => '9558', 'name' => 'Travessa 14', 'active' => '1'),
            array('id' => '897', 'city_id' => '9558', 'name' => 'Estrada do Mutum', 'active' => '1'),
            array('id' => '898', 'city_id' => '9558', 'name' => 'Rua 18', 'active' => '1'),
            array('id' => '899', 'city_id' => '9558', 'name' => 'Rua 7', 'active' => '1'),
            array('id' => '902', 'city_id' => '9558', 'name' => 'Av. Inácio Bittencourt Cardoso', 'active' => '0'),
            array('id' => '903', 'city_id' => '9558', 'name' => 'Rua Benedito Pereira de Oliveira (Rua 5)', 'active' => '0'),
            array('id' => '905', 'city_id' => '9558', 'name' => 'KM 22 Calcário', 'active' => '0'),
            array('id' => '906', 'city_id' => '9558', 'name' => 'Rua Olívio de Lima (Rua 4)', 'active' => '1'),
            array('id' => '907', 'city_id' => '9558', 'name' => 'Rua Antonio José da Silva (Rua 7)', 'active' => '1'),
            array('id' => '908', 'city_id' => '9558', 'name' => 'Rua Américo Rodrigues (Rua 21)', 'active' => '1'),
            array('id' => '909', 'city_id' => '9558', 'name' => 'Rua Francisco Alves Moreira (Rua 23)', 'active' => '1'),
            array('id' => '911', 'city_id' => '9558', 'name' => 'Rua Manoel Ciriaco da Silva (Rua 25)', 'active' => '1'),
            array('id' => '912', 'city_id' => '9558', 'name' => 'Rua Samuel Corsino (Rua 27)', 'active' => '1'),
            array('id' => '913', 'city_id' => '9558', 'name' => 'Rua Antonio Ferreira de Andrade (Rua 31)', 'active' => '1'),
            array('id' => '914', 'city_id' => '9558', 'name' => 'Rua José Garcia Lacerda (Rua 32)', 'active' => '1'),
            array('id' => '915', 'city_id' => '9558', 'name' => 'Rua Martin Célio Rosella (Rua 32)', 'active' => '1'),
            array('id' => '916', 'city_id' => '9558', 'name' => 'Rua José Camilo da Silva (Rua 35)', 'active' => '1'),
            array('id' => '917', 'city_id' => '9558', 'name' => 'Rua Belizário De Almeida (Rua 36)', 'active' => '1'),
            array('id' => '918', 'city_id' => '9558', 'name' => 'Rua João Elias Ramos (Rua 38)', 'active' => '1'),
            array('id' => '919', 'city_id' => '9558', 'name' => 'Rua Ver. Brasilino Gomes Amado (Rua 40)', 'active' => '1'),
            array('id' => '920', 'city_id' => '9558', 'name' => 'Rua Pr. Sebastião Ferreira Da Silva (Rua 42)', 'active' => '1'),
            array('id' => '921', 'city_id' => '9558', 'name' => 'Rua Pedro Camillo Zamparoni (17-A)', 'active' => '0'),
            array('id' => '922', 'city_id' => '9558', 'name' => 'BR 365', 'active' => '0'),
            array('id' => '925', 'city_id' => '9558', 'name' => 'Shopping Tangará', 'active' => '1'),
            array('id' => '927', 'city_id' => '9558', 'name' => 'Rua 68', 'active' => '0'),
            array('id' => '929', 'city_id' => '9558', 'name' => 'Rua Almerindo Xavier Cotrim (Rua 44)', 'active' => '1'),
            array('id' => '930', 'city_id' => '9558', 'name' => 'Rua Jovino Pedro do Nascimento (Rua 46)', 'active' => '1'),
            array('id' => '931', 'city_id' => '9558', 'name' => 'Rua Osvaldo Faria de Oliveira (Rua 48)', 'active' => '1'),
            array('id' => '932', 'city_id' => '9558', 'name' => 'Rua Oswaldo Donato (Rua)', 'active' => '1'),
            array('id' => '933', 'city_id' => '9558', 'name' => 'Rua José Vicente da Costa (Rua 52)', 'active' => '1'),
            array('id' => '934', 'city_id' => '9558', 'name' => 'Rua Erotildes Rodrigues Machado (Rua 54)', 'active' => '1'),
            array('id' => '935', 'city_id' => '9558', 'name' => 'Rua Pedro Kwiecinski (Rua 6A)', 'active' => '1'),
            array('id' => '936', 'city_id' => '9558', 'name' => 'Rua Francisco Souza da Cruz (Rua 8A)', 'active' => '1'),
            array('id' => '937', 'city_id' => '9558', 'name' => 'Rua Francisco Antonio da Silva (Rua 10A)', 'active' => '1'),
            array('id' => '938', 'city_id' => '9558', 'name' => 'Rua Francisco José de Mendonça (Rua 11A)', 'active' => '1'),
            array('id' => '939', 'city_id' => '9558', 'name' => 'Rua Prof. Maria Goretti Dhemer Wrobel (Rua 12A)', 'active' => '1'),
            array('id' => '940', 'city_id' => '9558', 'name' => 'Rodovia MT 358', 'active' => '0'),
            array('id' => '941', 'city_id' => '9558', 'name' => 'Rua das Perobas', 'active' => '0'),
            array('id' => '942', 'city_id' => '9558', 'name' => 'Rua Evelin Crestani (Rua 14)', 'active' => '0'),
            array('id' => '944', 'city_id' => '9558', 'name' => 'Rua 110', 'active' => '0'),
            array('id' => '945', 'city_id' => '9558', 'name' => 'Rua Atalibío Correia Batista ', 'active' => '0'),
            array('id' => '946', 'city_id' => '9558', 'name' => 'Rua 35', 'active' => '0'),
            array('id' => '947', 'city_id' => '9558', 'name' => '7 A', 'active' => '0'),
            array('id' => '948', 'city_id' => '9558', 'name' => 'Rua José Cândido Melhorança (24)', 'active' => '0'),
            array('id' => '949', 'city_id' => '9558', 'name' => 'Rua 42', 'active' => '0'),
            array('id' => '950', 'city_id' => '9558', 'name' => 'Rua Amilcar', 'active' => '0'),
            array('id' => '951', 'city_id' => '9558', 'name' => 'Shopping Popular', 'active' => '0'),
            array('id' => '952', 'city_id' => '9558', 'name' => 'Distrito de Progresso', 'active' => '0'),
            array('id' => '953', 'city_id' => '9558', 'name' => 'Rua Coxiponé', 'active' => '0'),
            array('id' => '954', 'city_id' => '9558', 'name' => 'Rua Manoel Gomes de Souza (14-A)', 'active' => '0'),
            array('id' => '955', 'city_id' => '9558', 'name' => 'Rua Nanci', 'active' => '0'),
            array('id' => '956', 'city_id' => '647', 'name' => 'Rua Guilherme Grunuwalde', 'active' => '0'),
            array('id' => '957', 'city_id' => '9558', 'name' => 'Rua 13A', 'active' => '0'),
            array('id' => '958', 'city_id' => '9558', 'name' => 'Rua 12-B', 'active' => '0'),
            array('id' => '959', 'city_id' => '9558', 'name' => 'Rua Francisco Carneiro Silva', 'active' => '0'),
            array('id' => '960', 'city_id' => '9558', 'name' => 'Rua 72 B', 'active' => '0'),
            array('id' => '961', 'city_id' => '9558', 'name' => 'Rua Roberto Valentim Cavalari', 'active' => '0'),
            array('id' => '962', 'city_id' => '9558', 'name' => 'Rua 24 A', 'active' => '0'),
            array('id' => '964', 'city_id' => '9558', 'name' => 'Av. Virgílio Favetti', 'active' => '0'),
            array('id' => '965', 'city_id' => '9558', 'name' => 'Rua 11', 'active' => '0'),
            array('id' => '967', 'city_id' => '283', 'name' => 'Estrada da Usina', 'active' => '0'),
            array('id' => '968', 'city_id' => '283', 'name' => 'Praça José Trindade', 'active' => '0'),
            array('id' => '969', 'city_id' => '283', 'name' => 'Rua 07 de Setembro', 'active' => '0'),
            array('id' => '970', 'city_id' => '283', 'name' => 'Rua 15 de Novembro', 'active' => '0'),
            array('id' => '971', 'city_id' => '283', 'name' => 'Rua Batista Neves', 'active' => '0'),
            array('id' => '972', 'city_id' => '283', 'name' => 'Rua Castelo Branco', 'active' => '0'),
            array('id' => '973', 'city_id' => '283', 'name' => 'Rua Diamantino', 'active' => '0'),
            array('id' => '974', 'city_id' => '283', 'name' => 'Rod. MT 160', 'active' => '1'),
            array('id' => '975', 'city_id' => '9558', 'name' => 'Rua 6A', 'active' => '0'),
            array('id' => '976', 'city_id' => '9558', 'name' => 'Rua 22A', 'active' => '0'),
            array('id' => '977', 'city_id' => '9558', 'name' => 'Rua Internacional', 'active' => '0'),
            array('id' => '978', 'city_id' => '9558', 'name' => 'Rua 1A', 'active' => '0'),
            array('id' => '979', 'city_id' => '9558', 'name' => 'Rua 50', 'active' => '0'),
            array('id' => '984', 'city_id' => '9558', 'name' => 'Perimetral', 'active' => '0'),
            array('id' => '985', 'city_id' => '9558', 'name' => 'Rua 14A', 'active' => '0'),
            array('id' => '987', 'city_id' => '9558', 'name' => 'Rua 09', 'active' => '0'),
            array('id' => '988', 'city_id' => '9558', 'name' => 'Rua 34', 'active' => '0'),
            array('id' => '989', 'city_id' => '9558', 'name' => 'Rua 30', 'active' => '0'),
            array('id' => '990', 'city_id' => '283', 'name' => 'Rua Tiradentes', 'active' => '0'),
            array('id' => '991', 'city_id' => '9558', 'name' => 'Rua 9A', 'active' => '0')
        );

    }
}
