<?php

use GuiaLocaliza\Companies\Admin\Domains\Models\Subcategory\Subcategory;
use Illuminate\Database\Seeder;

class SubcategoriesTableSedeer extends Seeder
{
    /**
     * @var Subcategory
     */
    private $subcategory;


    /**
     * SubcategoriesTableSedeer constructor.
     * @param Subcategory $this->subcategory
     */
    public function __construct(Subcategory $subcategory)
    {
        $this->subcategory = $subcategory;
    }

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $total = $this->subcategory->count();
        $subcategories = $this->subcategories();

        if($total === count($subcategories)) {
            return;
        }

        if($total <= 0) {

            foreach ($subcategories as $subcategory) {

                $this->subcategory->create([
                    'id' => $subcategory['id'],
                    'category_id' => $subcategory['category_id'],
                    'name' => $subcategory['name'],
                    'active' => true
                ]);

            }
            return;

        }

        foreach ($subcategories as $subcategory) {

            $total = $this->subcategory->where('name', $subcategory['name'])->count();
            if ($total <= 0) {
                $this->subcategory->create([
                    'id' => $subcategory['id'],
                    'category_id' => $subcategory['category_id'],
                    'name' => $subcategory['name'],
                    'active' => true
                ]);
            }

        }
    }

    private function subcategories()
    {
        
        return array(
            array('id' => '1','category_id' => '659','name' => 'Fabricação, Indústrias, Têxtil'),
            array('id' => '4','category_id' => '55','name' => 'Restaurantes, Lanchonetes, Lanches'),
            array('id' => '5','category_id' => '246','name' => 'Modas, Confecção, Confecções, Bazar, Boutiques, Adulto, Infanto Juvenil'),
            array('id' => '6','category_id' => '151','name' => 'Eletrônicos, Consertos'),
            array('id' => '7','category_id' => '40','name' => 'Eletricistas, Encanador, Encanadores, Limpezas, Consertos, Montagem, Montagens, Reparos, Reformas'),
            array('id' => '8','category_id' => '87','name' => 'Musculação, Musculações, Malhação, Malhações, fitness'),
            array('id' => '10','category_id' => '482','name' => 'Piscinas, Natações, Ginásticas'),
            array('id' => '11','category_id' => '106','name' => 'Distribuidoras e Conveniências, Festas, Eventos'),
            array('id' => '12','category_id' => '140','name' => 'Escritórios Contábeis, Contabilidades, Contabilistas, Contador'),
            array('id' => '13','category_id' => '148','name' => 'Policiais, Delegados, Delegadas, Policial'),
            array('id' => '14','category_id' => '18','name' => 'Arquiteturas, Projetos, Construção, Construções, Uranismo'),
            array('id' => '15','category_id' => '20','name' => 'Arquitetos, Engenheiros, Projetos, Urbanismo'),
            array('id' => '16','category_id' => '21','name' => 'Material, Construções'),
            array('id' => '17','category_id' => '25','name' => 'Informáticas, Programas, Softs, Sofware, Desenvolvimentos, Desenvolvedores'),
            array('id' => '18','category_id' => '26','name' => 'Transportadoras, Logísticas, Turismos, Viagem'),
            array('id' => '20','category_id' => '82','name' => 'Associados, Associação Comercial e Empresarial'),
            array('id' => '22','category_id' => '34','name' => 'Turismos'),
            array('id' => '23','category_id' => '35','name' => 'Administradora, Consultor, Consultores, Imobiliários, Locação, Locações, Imóveis, Corretores, Terrenos, Casas, Compras, Vendas, Aluguel, Aluguéis'),
            array('id' => '24','category_id' => '36','name' => 'Revendedor, Revendedores, Revenda, Compra e Vendas, Automóvel, Veículos, Garagem'),
            array('id' => '25','category_id' => '39','name' => 'Cartão de Créditos, Cartões, Financiamentos, Empréstimos, Capitalização, Capitalizações'),
            array('id' => '26','category_id' => '41','name' => 'Distribuidoras, Combustível'),
            array('id' => '28','category_id' => '44','name' => 'Cooperados, Associados, Associação, Associações'),
            array('id' => '29','category_id' => '86','name' => 'Viagem, Turismos, Passagem, Passagens, Aéreas, Marítimas, Terrestres'),
            array('id' => '31','category_id' => '78','name' => 'Auto Peças, Automóvel, Carros, Veículos, Automotivas'),
            array('id' => '32','category_id' => '70','name' => 'Projetos, Agropecuários, Agrícolas, Agriculturas, Rural, Rurais'),
            array('id' => '33','category_id' => '269','name' => 'Seguranças'),
            array('id' => '35','category_id' => '133','name' => 'Petshop, Veterinárias, PetShop, Pet shop'),
            array('id' => '36','category_id' => '123','name' => 'Tabelião, Órgãos Públicos, Tabeliões'),
            array('id' => '38','category_id' => '219','name' => 'Oficinas Mecânicas, Motocicletas'),
            array('id' => '40','category_id' => '43','name' => 'Transportadoras, Logísticas, Fretes'),
            array('id' => '41','category_id' => '157','name' => 'Embalagem'),
            array('id' => '42','category_id' => '277','name' => 'Conveniências, Bebidas'),
            array('id' => '43','category_id' => '484','name' => 'Distribuidores, Energias, Elétricas'),
            array('id' => '44','category_id' => '46','name' => 'Órgão Público, Governos, Autarquias'),
            array('id' => '45','category_id' => '485','name' => 'Secador, Agronegócios, Armazém, Armazenagem, Armazenagens, Secadores'),
            array('id' => '46','category_id' => '228','name' => 'Pousadas, Recreativos'),
            array('id' => '49','category_id' => '487','name' => 'Conselhos Tutelares, Órgãos Públicos'),
            array('id' => '50','category_id' => '488','name' => 'Odontologias, Odontológicas, Odontologistas'),
            array('id' => '51','category_id' => '490','name' => 'Órgãos Públicos'),
            array('id' => '52','category_id' => '388','name' => 'Órgãos Públicos'),
            array('id' => '53','category_id' => '138','name' => 'Construção, Construções, Construtor'),
            array('id' => '55','category_id' => '89','name' => 'Fisioterapeutas'),
            array('id' => '56','category_id' => '130','name' => 'Consultas Médicas'),
            array('id' => '57','category_id' => '128','name' => 'Consultórios, Raio X, RaioX, Consultas, Radiologistas'),
            array('id' => '58','category_id' => '491','name' => 'Médicas, Centros Médicos'),
            array('id' => '60','category_id' => '135','name' => 'Colchão, Colchoarias'),
            array('id' => '61','category_id' => '79','name' => 'Serralheiros, Metalúrgicos, Metalurgias'),
            array('id' => '62','category_id' => '56','name' => 'Cabeleireiras, Salões, Belezas, Manicure, Pedicure, Barbeiros, Barbearias'),
            array('id' => '64','category_id' => '243','name' => 'Oficinas Mecânicas'),
            array('id' => '65','category_id' => '198','name' => 'Paróquias, Capelas, Catedral, Catedrais, Evangélicas, Evangélicos, Dioceses, Prelazias, Católicos, Católicas'),
            array('id' => '66','category_id' => '208','name' => 'Lavar, Lavagem, Lavagens, Limpezas'),
            array('id' => '69','category_id' => '299','name' => 'Borracharias, Borrachas, Borracheiros'),
            array('id' => '70','category_id' => '177','name' => 'Remédios, Medicamentos, Farmacêuticas, Manipulações, Produtos Farmacêuticos, Cosméticos'),
            array('id' => '74','category_id' => '236','name' => 'Refrigerações, Climatizações'),
            array('id' => '76','category_id' => '185','name' => 'Fotógrafos, Fotógrafas'),
            array('id' => '77','category_id' => '163','name' => 'Órgãos Públicos, Educação, Educar, Estudos, Estudar'),
            array('id' => '78','category_id' => '85','name' => 'Sorvetes'),
            array('id' => '79','category_id' => '167','name' => 'Educação, Educar, Estudos, Estudar'),
            array('id' => '81','category_id' => '28','name' => 'Comércios'),
            array('id' => '82','category_id' => '117','name' => 'Modas'),
            array('id' => '83','category_id' => '170','name' => 'Músicas, Musical, Artes'),
            array('id' => '84','category_id' => '1','name' => 'Pescarias'),
            array('id' => '85','category_id' => '495','name' => 'Mármores, Pedras'),
            array('id' => '86','category_id' => '59','name' => 'Flores, Plantas, Decoração, Jardinagem, Jardinagens, Decorações'),
            array('id' => '87','category_id' => '58','name' => 'Associações Culturais, Desportivas, Sociais, Beneficientes, Filantrópicas, Associados, Entidades'),
            array('id' => '90','category_id' => '60','name' => 'Vidros, Vidraceiros, Construção, Construções'),
            array('id' => '91','category_id' => '104','name' => 'Órgãos Públicos'),
            array('id' => '92','category_id' => '108','name' => 'Bicicletas'),
            array('id' => '93','category_id' => '109','name' => 'Acessórios Femininos, Modas, Femininas'),
            array('id' => '94','category_id' => '115','name' => 'Festas, Eventos, Casamentos, Formaturas'),
            array('id' => '95','category_id' => '120','name' => 'Municipal, Órgãos Públicos, Poder Legislativo'),
            array('id' => '97','category_id' => '656','name' => 'Produtos para Bebês e Crianças'),
            array('id' => '99','category_id' => '313','name' => 'Dançarinos, Dançarinas, Bailarinos, Bailarinas'),
            array('id' => '100','category_id' => '655','name' => 'Veterinárias'),
            array('id' => '101','category_id' => '496','name' => 'Poder Judiciário, Órgãos Públicos, Justiças, Comarcas, Tribunal'),
            array('id' => '103','category_id' => '188','name' => 'Frigoríficos, Indústrias, Fábricas'),
            array('id' => '105','category_id' => '189','name' => 'Serviços Funeral, Funerais'),
            array('id' => '106','category_id' => '84','name' => 'Autocenter, Oficinas, Mecânicas, Automóveis'),
            array('id' => '108','category_id' => '187','name' => 'Chapeamentos, Oficinas Mecânicas, Pinturas, Automóvel, Automóveis'),
            array('id' => '109','category_id' => '190','name' => 'Construção, Construções, Reformas, Obras'),
            array('id' => '110','category_id' => '286','name' => 'Escolinhas, Esportes'),
            array('id' => '111','category_id' => '262','name' => 'Terraplanagens, Locação de Máquinas'),
            array('id' => '112','category_id' => '191','name' => 'Impressos, Impressão, Impressões, Comunicações visuais, Publicidades, Propagandas, Painéis, Painel'),
            array('id' => '113','category_id' => '212','name' => 'Marmitas, Marmitex, Restaurantes, Refeição, Refeições'),
            array('id' => '114','category_id' => '211','name' => 'Confecção, Fábricas, Indústrias, Uniformes, Malhas'),
            array('id' => '115','category_id' => '196','name' => 'Hospital, Médicos, Medicinas, Enfermarias, Enfermagem, Enfermagens, Enfermeiros, Enfermeiras, Pronto Socorro, Consultórios, Pronto Atendimento'),
            array('id' => '116','category_id' => '197','name' => 'Hotéis, Hotelarias, Hospedarias, Hospedagem, Hospedagens'),
            array('id' => '117','category_id' => '199','name' => 'Igrejas, Congregação, Religião, Religiões'),
            array('id' => '119','category_id' => '251','name' => 'Locação, Locações de Som, Sonorização, Sonorizações, Luz, Palcos, Eventos, Festas, Formaturas, Casamentos, Shows'),
            array('id' => '120','category_id' => '295','name' => 'Colégios, Formação, Formações, Educação, Ensino'),
            array('id' => '122','category_id' => '279','name' => 'Casa de Empréstimos, Financeiras, Financiamentos'),
            array('id' => '123','category_id' => '238','name' => 'Representação, Comercial'),
            array('id' => '124','category_id' => '105','name' => 'Festas e Eventos'),
            array('id' => '125','category_id' => '205','name' => 'Jornal, Imprensa, Notícias, Informação, Informações'),
            array('id' => '126','category_id' => '381','name' => 'Prémoldados, Indústrias, Fábricas'),
            array('id' => '127','category_id' => '289','name' => 'Nutrições, Consultas'),
            array('id' => '129','category_id' => '376','name' => 'Pastel, Pastéis, Lanches, Lanchonetes'),
            array('id' => '130','category_id' => '239','name' => 'Atacadão, Supermercados, Hipermercados, Mercados, Mercearias, Empórios'),
            array('id' => '131','category_id' => '206','name' => 'Exames'),
            array('id' => '132','category_id' => '202','name' => 'Lanhouses, Informáticas, Internets'),
            array('id' => '135','category_id' => '209','name' => 'Oficinas Mecânicas, Hidráulicas'),
            array('id' => '136','category_id' => '90','name' => 'Advogadas, OAB'),
            array('id' => '137','category_id' => '281','name' => 'Gravações, Produção, Produções, Propagandas, Publicidades, Áudios, Locução, Locuções, Locutor, Locutores'),
            array('id' => '138','category_id' => '124','name' => 'Loterias'),
            array('id' => '139','category_id' => '267','name' => 'Agronegócios'),
            array('id' => '140','category_id' => '213','name' => 'Mármores, Pedras, Construção, Construções'),
            array('id' => '141','category_id' => '504','name' => 'Auto Center, Autocenter, Caminhão'),
            array('id' => '142','category_id' => '505','name' => 'Oficinas Mecânicas'),
            array('id' => '144','category_id' => '222','name' => 'Emplacamento'),
            array('id' => '145','category_id' => '253','name' => 'Alimentos, Atacados, Atacadistas, Atacadão'),
            array('id' => '146','category_id' => '290','name' => 'Aquecedores, Solares'),
            array('id' => '148','category_id' => '507','name' => 'Seguranças, Trabalhos, Trabalhadores'),
            array('id' => '149','category_id' => '679','name' => 'Pintor, Pinturas'),
            array('id' => '150','category_id' => '508','name' => 'Propaganda Volante, Carros de Som, Publicidades, Propagandas'),
            array('id' => '151','category_id' => '509','name' => 'Perfumes, Belezas, Maquiagem, Maquiagens'),
            array('id' => '153','category_id' => '217','name' => 'Motéis, Hospedagem, Hospedagens'),
            array('id' => '154','category_id' => '218','name' => 'Mototaxis, Mototaxistas, Motos, Táxis'),
            array('id' => '155','category_id' => '511','name' => 'Investimentos'),
            array('id' => '156','category_id' => '458','name' => 'Cereais, Grãos, Agronegócios, Indústrias, Fábricas'),
            array('id' => '157','category_id' => '373','name' => 'Orelhão, Orelhões'),
            array('id' => '158','category_id' => '653','name' => 'Produtos Farmacêuticos e Cosméticos'),
            array('id' => '159','category_id' => '74','name' => 'Pão, Pães'),
            array('id' => '160','category_id' => '69','name' => 'Materiais de Escritórios'),
            array('id' => '161','category_id' => '310','name' => 'Construtor, Construção, Construções, Obras'),
            array('id' => '162','category_id' => '73','name' => 'Peixes'),
            array('id' => '164','category_id' => '431','name' => 'Pescarias'),
            array('id' => '165','category_id' => '293','name' => 'Pisciculturas, Peixes'),
            array('id' => '166','category_id' => '392','name' => 'Locação, Locações, Aluguéis'),
            array('id' => '167','category_id' => '433','name' => 'Órgãos Públicos, Consultas Médicas, Médicos'),
            array('id' => '168','category_id' => '226','name' => 'Delegacias, Órgãos Públicos, Segurança, Delegados, Justiças'),
            array('id' => '169','category_id' => '423','name' => 'Poder Executivo, Órgãos Públicos, Secretarias Municipais, Municipal'),
            array('id' => '170','category_id' => '230','name' => 'Pregões'),
            array('id' => '171','category_id' => '514','name' => 'Defesa do Consumidor, Consumidores, Proteção, Órgãos Públicos, Procons'),
            array('id' => '172','category_id' => '515','name' => 'Promotor, Órgãos Públicos, Poder Judiciário'),
            array('id' => '173','category_id' => '231','name' => 'Prontos Socorros, Prontos Atendimentos, Emergências, Saúdes, Médicos, Enfermeiros, Enfermeiras, Enfermarias, Enfermagens, Enfermagem, Órgãos Públicos, PA'),
            array('id' => '174','category_id' => '234','name' => 'Oficinas Mecânicas'),
            array('id' => '175','category_id' => '339','name' => 'Auto Elétricas, Autoelétricas, Oficinas Mecânicas'),
            array('id' => '177','category_id' => '235','name' => 'Imprensa, Impressa, Publicidades, Propagandas, Notícias, Informação, Informções'),
            array('id' => '179','category_id' => '517','name' => 'Refeição, Refeições'),
            array('id' => '181','category_id' => '245','name' => 'Terminal, Estação, Rodoviária'),
            array('id' => '182','category_id' => '518','name' => 'Oficinas Mecânicas'),
            array('id' => '184','category_id' => '248','name' => 'Sapateiros, Sapatos, Calçados'),
            array('id' => '185','category_id' => '311','name' => 'Assistência Técnica, Máquinas, Motores'),
            array('id' => '186','category_id' => '276','name' => 'Associados, Associação de Classe, Sindicalistas'),
            array('id' => '187','category_id' => '409','name' => 'Reciclável, Recicláveis, Reciclagens'),
            array('id' => '188','category_id' => '165','name' => 'Estudos, Formação, Formações, Graduação, Graduações, Educação, Educações'),
            array('id' => '190','category_id' => '377','name' => 'Tabacos, Cigarros'),
            array('id' => '191','category_id' => '261','name' => 'Imprensas, Comunicação, Comunicações, Publicidades, Propagandas, Informações, Informação'),
            array('id' => '192','category_id' => '256','name' => 'Tapeceiros'),
            array('id' => '193','category_id' => '258','name' => 'Taxis, Taxistas'),
            array('id' => '195','category_id' => '264','name' => 'Torneiros, Oficinas Mecânicas'),
            array('id' => '196','category_id' => '97','name' => 'Artesões, Artesãos, Artes, Artesã'),
            array('id' => '198','category_id' => '460','name' => 'Fábricas, Indústrias, Destilarias'),
            array('id' => '200','category_id' => '24','name' => 'Aluguéis, Locação, Locações'),
            array('id' => '201','category_id' => '158','name' => 'Trabalhos'),
            array('id' => '202','category_id' => '322','name' => 'Cobrador, Cobradores'),
            array('id' => '203','category_id' => '342','name' => 'Organizadores, Promotores'),
            array('id' => '208','category_id' => '49','name' => 'Sementes, Defensivos, Fertilizantes, Adubos, Agrotóxicos, Agronegócios'),
            array('id' => '209','category_id' => '221','name' => 'Manutenção, Manutenções'),
            array('id' => '210','category_id' => '134','name' => 'Associação, Associações, Associados, Sócios'),
            array('id' => '211','category_id' => '368','name' => 'Montagens, Instalação, Instalações'),
            array('id' => '213','category_id' => '194','name' => 'Reboques'),
            array('id' => '214','category_id' => '328','name' => 'Cerimoniais, Festas, Eventos, Casamentos, formaturas'),
            array('id' => '215','category_id' => '468','name' => 'Areal, Areais'),
            array('id' => '217','category_id' => '530','name' => 'Cafés'),
            array('id' => '218','category_id' => '175','name' => 'Fomentos, Assessoria Financeiras'),
            array('id' => '220','category_id' => '657','name' => 'Indústrias, Têxtil, Têxtis, Malharias'),
            array('id' => '222','category_id' => '48','name' => 'Autoelétricas, Oficinas Mecânicas'),
            array('id' => '223','category_id' => '77','name' => 'Auto Postos, Combustível, Troca de Óleos'),
            array('id' => '224','category_id' => '126','name' => 'Chaves'),
            array('id' => '225','category_id' => '174','name' => 'Extintor'),
            array('id' => '226','category_id' => '543','name' => 'Indústrias, Fábricas, Limpezas'),
            array('id' => '233','category_id' => '169','name' => 'Cursos, Formação, Formações'),
            array('id' => '234','category_id' => '121','name' => 'Gráficas'),
            array('id' => '235','category_id' => '173','name' => 'Festas, Locação, Locações, Eventos'),
            array('id' => '238','category_id' => '539','name' => 'Trabalho, Trabalhador, Trabalhadores'),
            array('id' => '239','category_id' => '447','name' => 'Aluguéis, Locação, Locações, Obras, Construção'),
            array('id' => '240','category_id' => '540','name' => 'Consultas, Médicas, Médicos'),
            array('id' => '243','category_id' => '445','name' => 'Bebês, Crianças, Presentes'),
            array('id' => '244','category_id' => '542','name' => 'Ferrovias, Logísticas, Transportadoras'),
            array('id' => '246','category_id' => '410','name' => 'Clínicas, Oftalmologias, Oftalmologistas'),
            array('id' => '247','category_id' => '544','name' => 'Distribuidoras'),
            array('id' => '248','category_id' => '204','name' => 'Jóias, Semijóias, Relójos, Semi-jóias'),
            array('id' => '249','category_id' => '142','name' => 'Decorações, Decorar, Decorador, Decoradoras, Decoradores'),
            array('id' => '250','category_id' => '338','name' => 'Escolas, Infantis, Escolinhas'),
            array('id' => '251','category_id' => '360','name' => 'Indústrias, Fábricas'),
            array('id' => '252','category_id' => '88','name' => 'Mercados, Mercearias, Supermercados'),
            array('id' => '254','category_id' => '552','name' => 'Ortopedias, Ortopédicas, Ortopédicos'),
            array('id' => '258','category_id' => '556','name' => 'Galerias, Artes, Culturais, Cultura'),
            array('id' => '259','category_id' => '557','name' => 'Máquinas, Decoração, Decorações'),
            array('id' => '260','category_id' => '558','name' => 'Pré Vestibulares, Vestibular'),
            array('id' => '261','category_id' => '156','name' => 'Indústrias, Fábrica, Móvel'),
            array('id' => '262','category_id' => '559','name' => 'Furgão, Vendas, Reformas'),
            array('id' => '266','category_id' => '352','name' => 'Consultórios, Massagem, Massagens'),
            array('id' => '273','category_id' => '567','name' => 'Corretores'),
            array('id' => '274','category_id' => '568','name' => 'Hortaliças, Frutas, Frutarias, Verduras, Verdurarias'),
            array('id' => '277','category_id' => '571','name' => 'Penitenciárias'),
            array('id' => '278','category_id' => '572','name' => 'Jardinagens, Paisagismos'),
            array('id' => '279','category_id' => '369','name' => 'Avicultura, Aviários, Avículas, Avícolas, Aves'),
            array('id' => '280','category_id' => '437','name' => 'Máquinas, Equipamentos'),
            array('id' => '281','category_id' => '573','name' => 'Financiamentos, Empréstimos, Financeiras'),
            array('id' => '282','category_id' => '574','name' => 'Hotel, Hotéis, Turismos'),
            array('id' => '283','category_id' => '335','name' => 'Comércios, Indústrias, Minérios, Mineração, Minerações, Mineradoras'),
            array('id' => '284','category_id' => '575','name' => 'Locações, Locação'),
            array('id' => '286','category_id' => '580','name' => 'Consultórios, Clínicas, Consultas, Veterinários, Veterinárias'),
            array('id' => '288','category_id' => '581','name' => 'Telefones, Celulares, Celular, Assistência Técnica, Consertos, Telefonias'),
            array('id' => '289','category_id' => '93','name' => 'Costureiras'),
            array('id' => '290','category_id' => '582','name' => 'Neurocirurgias, Médicos, Médicas'),
            array('id' => '292','category_id' => '350','name' => 'Consultorias, Assessorias, Ambiental'),
            array('id' => '295','category_id' => '127','name' => 'Filmes, Lazer, Culturas, Entretenimentos'),
            array('id' => '299','category_id' => '315','name' => 'Lubrificação, Oficinas Mecânicas'),
            array('id' => '300','category_id' => '214','name' => 'Hidráulicos, Oficinas Mecânicas'),
            array('id' => '301','category_id' => '588','name' => 'Telemensagem'),
            array('id' => '302','category_id' => '98','name' => 'Comércio, Comércios'),
            array('id' => '304','category_id' => '596','name' => 'Caças, Pescas, Pescador, Pescadores, Pescarias'),
            array('id' => '305','category_id' => '599','name' => 'Enxoval'),
            array('id' => '310','category_id' => '195','name' => 'Telefones, Agendas Telefônicas'),
            array('id' => '311','category_id' => '590','name' => 'Limpezas, Lava-Jato, Lava-Rápido, Lavador'),
            array('id' => '312','category_id' => '467','name' => 'Roupas, Modas, Confecção, Confecções, Costureiras'),
            array('id' => '313','category_id' => '604','name' => 'Produtos e Equipamentos para Informáticas'),
            array('id' => '314','category_id' => '605','name' => 'Cursos e Treinamentos Profissionalizantes'),
            array('id' => '317','category_id' => '67','name' => 'Locação, Locações, Aluguéis, Veículos, Automóveis, Automóvel, Garagem, Garagens'),
            array('id' => '318','category_id' => '91','name' => 'Distribuidoras'),
            array('id' => '319','category_id' => '242','name' => 'Chopp, Bar, Bares'),
            array('id' => '320','category_id' => '421','name' => 'Rodoviários, Logísticas'),
            array('id' => '324','category_id' => '611','name' => 'Pneumáticos'),
            array('id' => '337','category_id' => '591','name' => 'Telefones, Telefonias, Rádio Amadores, Comunicadores'),
            array('id' => '339','category_id' => '413','name' => 'Tapeçarias'),
            array('id' => '343','category_id' => '183','name' => 'Fonoaudiólogas, Fonoaudiólogos'),
            array('id' => '345','category_id' => '621','name' => 'Refeição, Refeições, Lanchonetes, Restaurantes, Churrascos, '),
            array('id' => '346','category_id' => '330','name' => 'Fábricas, Marcenarias, Indústrias'),
            array('id' => '347','category_id' => '278','name' => 'Fábricas, Ração, Rações'),
            array('id' => '348','category_id' => '622','name' => 'Ar Condicionados, Auto Center, Auto Elétricas, Refrigerações, Automotivas'),
            array('id' => '350','category_id' => '625','name' => 'Sinucas, Jogos, Diversão, Diversões'),
            array('id' => '352','category_id' => '545','name' => 'Projetos'),
            array('id' => '353','category_id' => '628','name' => 'Indústrias, Fá¡bricas, Madeiras, Madeireiras'),
            array('id' => '359','category_id' => '143','name' => 'Infantil, Crianças, Infantis'),
            array('id' => '360','category_id' => '316','name' => 'Material, Materiais, Construção, Construções'),
            array('id' => '364','category_id' => '1','name' => 'Transportadoras, Logísticas, Seguranças'),
            array('id' => '365','category_id' => '64','name' => 'Autoescolas'),
            array('id' => '367','category_id' => '80','name' => 'Bancos, Cooperados, Associados, Cartão de Créditos, Cartões, Financiamentos, Empréstimos, Capitalização, Capitalizações'),
            array('id' => '368','category_id' => '81','name' => 'Fundação'),
            array('id' => '370','category_id' => '380','name' => 'Prémoldados, Pré Moldados, Indústrias, Fábricas'),
            array('id' => '374','category_id' => '658','name' => 'Têxtil, Indústrias, Fábricas'),
            array('id' => '375','category_id' => '399','name' => 'Produtos Químicos e Inflamáveis, Infamável'),
            array('id' => '377','category_id' => '665','name' => 'Projetos e Soluções de Segurança'),
            array('id' => '378','category_id' => '669','name' => 'Transportes, Logísticas'),
            array('id' => '379','category_id' => '670','name' => 'Fotos, Fotografias, Filmagens'),
            array('id' => '380','category_id' => '671','name' => 'Materiais de Construção, Construções, Material'),
            array('id' => '381','category_id' => '674','name' => 'Artefatos de Cimentos e Concretos'),
            array('id' => '382','category_id' => '675','name' => 'Assessoria Rural'),
            array('id' => '384','category_id' => '63','name' => 'Comemorativas, Promocionais'),
            array('id' => '385','category_id' => '68','name' => 'Locadoras de Vídeos'),
            array('id' => '386','category_id' => '94','name' => 'Comércios, Aluguéis, Locação, Locações'),
            array('id' => '387','category_id' => '95','name' => 'Comércios, Instalações'),
            array('id' => '388','category_id' => '141','name' => 'Xerox'),
            array('id' => '389','category_id' => '144','name' => 'Assistências Técnicas'),
            array('id' => '390','category_id' => '159','name' => 'Aluguéis, Locação, Locações'),
            array('id' => '391','category_id' => '291','name' => 'Instalação, Manutenção, Elétricos'),
            array('id' => '392','category_id' => '266','name' => 'Logísticas, Transportadoras'),
            array('id' => '393','category_id' => '172','name' => 'Garagem, Garagens'),
            array('id' => '394','category_id' => '176','name' => 'Indústrias, Fábricas'),
            array('id' => '395','category_id' => '182','name' => 'Financiamentos, Empréstimos'),
            array('id' => '396','category_id' => '186','name' => 'Populares, Comercial, Comércios, Lojas'),
            array('id' => '397','category_id' => '193','name' => 'Comércios, Lojas'),
            array('id' => '398','category_id' => '201','name' => 'Importações, Exportações'),
            array('id' => '399','category_id' => '215','name' => 'Psicologias'),
            array('id' => '400','category_id' => '224','name' => 'Construções, Manutenções'),
            array('id' => '401','category_id' => '233','name' => 'Dentistas, Odontologias'),
            array('id' => '402','category_id' => '272','name' => 'Produtor Rural, Produtores Rarais, Agronegócios, Agropecuários, Agropecuárias'),
            array('id' => '403','category_id' => '292','name' => 'Eletrificação, Projetos de Instalação, Instalações, Eletricidade, Elétricos'),
            array('id' => '404','category_id' => '296','name' => 'Comércios'),
            array('id' => '405','category_id' => '305','name' => 'Comércios, Indústrias'),
            array('id' => '406','category_id' => '321','name' => 'Eletricidades, Elétricas'),
            array('id' => '407','category_id' => '323','name' => 'Projetos Agropecuários, Agrícolas, Agronegócios'),
            array('id' => '408','category_id' => '326','name' => 'Instalação, Portão, Seguranças'),
            array('id' => '410','category_id' => '348','name' => 'Topógrafo, Agrimensores, Agrimensuras, Topografias'),
            array('id' => '411','category_id' => '366','name' => 'Aviações, Agrícolas'),
            array('id' => '412','category_id' => '370','name' => 'Embreagem, Autopeças'),
            array('id' => '413','category_id' => '378','name' => 'Fábricas, Indústrias'),
            array('id' => '414','category_id' => '379','name' => 'Consultoras, Vendedores, Vendedoras, Revendedores, Revendedoras'),
            array('id' => '415','category_id' => '382','name' => 'Comércios'),
            array('id' => '416','category_id' => '398','name' => 'Fábricas, Indústrias'),
            array('id' => '418','category_id' => '434','name' => 'Portais, Sites, Webisites'),
            array('id' => '419','category_id' => '441','name' => 'Eletrônicas'),
            array('id' => '420','category_id' => '472','name' => 'Metal, Metais, Metalúrgicas, Metalúrgicos'),
            array('id' => '421','category_id' => '547','name' => 'Veterinárias'),
            array('id' => '422','category_id' => '683','name' => 'Tribunal Regional Eleitoral, TRE, Justiça Eleitoral, Poder Judiciário'),
            array('id' => '423','category_id' => '598','name' => 'Enxoval, Fábricas, Indústrias'),
            array('id' => '424','category_id' => '606','name' => 'Advocacias, Advogados, OAB'),
            array('id' => '425','category_id' => '612','name' => 'Autopeças, Auto Peças, Borrachão, Borrachões, Borracharias'),
            array('id' => '426','category_id' => '629','name' => 'Certificadoras, Digitais'),
            array('id' => '427','category_id' => '176','name' => 'Fábricas, Indústrias'),
            array('id' => '428','category_id' => '640','name' => 'Fábricas, Indústrias'),
            array('id' => '429','category_id' => '642','name' => 'Fábricas, Indústrias'),
            array('id' => '430','category_id' => '643','name' => 'Fábricas, Indústrias'),
            array('id' => '431','category_id' => '644','name' => 'Associações, Associados, Profissionais'),
            array('id' => '432','category_id' => '647','name' => 'Transportadoras, Logísticas'),
            array('id' => '433','category_id' => '649','name' => 'Indústrias, Fábricas'),
            array('id' => '434','category_id' => '663','name' => 'Construtoras, Construção, Construções, Obras'),
            array('id' => '435','category_id' => '667','name' => 'Lanches, Pizzas, Fastfood'),
            array('id' => '436','category_id' => '570','name' => 'Modas, Têxteis, Vestuários'),
            array('id' => '437','category_id' => '524','name' => 'Representações Comerciais'),
            array('id' => '438','category_id' => '336','name' => 'Empreendimentos Imobiliários'),
            array('id' => '439','category_id' => '411','name' => 'Dermatológicos, Dermatologistas'),
            array('id' => '440','category_id' => '684','name' => 'Indústrias, Comércios, Distribuidoras, Metais')
          );
          
    }
}
