<?php
//file : app/config/constants.php

return [

    'ERROR_PROCESS_OAUTH' => 'Houve um erro na operação. Por favor tente novamente!',
    'OAUTH_NOT_CONNECTED' => 'Não há nenhuma conta vinculada a este aplicativo no momento.',
    'OAUTH_DENIED' => 'Nós precisamos de sua permissão para realizar a ação que nos pediu.',
    'ERROR_ROUTE' => '404 - Sorry, the page you are looking for could not be found.',
    'ERROR_PASSWORD_IS_NOT_IDENTICAL' => 'As senhas não são iguais.',
    'PASSWORD_IS_CURT' => 'A senha deve conter no miníno 6 caracteres.',
    'APP_IS_NOT_ASSOCIATED' => 'Este aplicativo não está associado a nenhuma conta.',
    'INVALID_EMAIL_OR_PASSWORD' => 'O e-mail ou a senha inseridos estão incorretos.',
    'PLEASE_ENTER_NAME_VALID' => 'Por favor, informe seu nome corretamente.',
    'PLEASE_ENTER_PASSWORD_VALID' => 'Esta não é uma senha válida.',
    'PASSWORD_CHANGE' => 'Sua senha foi alterada com sucesso.',
    'WEAK_PASSWORD' => 'Sua Senha foi detectada como insegura!',
    'NO_WHITE_SPACE' => 'Não é permitido espaço em branco na Senha.',
    'SHA1_INVALID' => 'Esta não é uma chave válida',
    'TOKEN_INVALID_OR_NOT_FOUND' => 'Esta é uma chave inválida ou expirado!',
    'PLEASE_ENTER_EMAIL_VALID' => 'Por favor, informe seu email corretamente.',
    'PLEASE_EMAIL_EMPTY_RECOVER' => 'Informe o email cadastrado.',
    'USER_IS_REGISTERED' => 'Já temos um cadastro com seu e-mail. Experimente fazer login.',
    'USER_IS_NOT_REGISTERED' => 'O e-mail inserido não foi encontrado. Verifique se o e-mail foi digitado corretamente.',
    'SUBJECT_RECOVER_PASSWORD' => 'Redefinição de senha',
    'SUBJECT_RESET_PASSWORD' => 'Sua senha foi alterada',
    'SUBJECT_NEW_PASSWORD' => 'Nova senha de acesso foi gerada',
    'SUBJECT_NEW_USER_ADMIN' => 'Cadastro de usuário administrativo',
    'SUBJECT_CONFIRM_EMAIL' => 'Confirmação de E-mail',
    'MSG_FLASH_DATA_CHANGED' => 'Os dados foram alterados com sucesso.',
    'MSG_USER_CREATE_SUCCESS' => 'Usuário adminstrativo cadastrado com sucesso.',
    'MSG_USER_CREATE_ERROR' => 'Usuário adminstrativo já encontra-se cadastrado.',
    'MSG_USER_UPDATE_SUCCESS' => 'Usuário adminstrativo alterado com sucesso.',
    'MSG_USER_UPDATE_ERROR' => 'Houve um erro ao tentar alterar os dados de usuário.',
    'MSG_USER_REMOVE_SUCCESS' => 'Usuário adminstrativo removido com sucesso.',
    'MSG_USER_RESTORE_SUCCESS' => 'Usuário adminstrativo restaurado com sucesso.',
    'MSG_USER_NEW_PASSWORD_SUCCESS' => 'Uma nova senha foi gerada e enviada por email com sucesso.',
    'MSG_DATA_REMOVED_SUCCESS' => 'Os dados foram removidos com sucesso.',
    'MSG_DATA_PERMISSION_ACTIVE_SUCCESS' => 'A permissão foi ativada com sucesso.',
    'MSG_DATA_PERMISSION_REVOKE_SUCCESS' => 'A permissão foi revogada com sucesso.',
    'MSG_DATA_REGISTERED_SUCCESS' => 'Os dados foram cadastrados com sucesso.',
    'MSG_DATA_UPDATE_SUCCESS' => 'Os dados foram alterados com sucesso.',
    'MSG_DATA_EQUALS_REGISTERED' => 'Dados iguais já encontra-se cadastrados.',
    'MSG_PASSWORD_CURRENT_NOT_EQUALS' => 'Sua atual não corresponde.',
    'MSG_PASSWORD_IS_NOT_IDENTICAL' => 'As senhas não são iguais.',
    'MSG_NOT_AUTHORIZED'=> 'Erro 403.1 - Acesso de execução negado.',
    'MSG_PERMISSIONS_UPDATE_SUCCESS'=> 'Permissões administrativas canceladas com sucesso.',
    'PREPEND_INPUT_SELECT' => 'Selecione...',
    'ERROR_PROCESS' => 'Ocorreu um erro durante o processamento de sua solicitação. Por favor, tente novamente mais tarde.',
    'WITHOUT_AUTHORIZATION' => '403 - Proibido: Acesso negado. Você não tem permissão para exibir este diretório ou esta página usando as credenciais que você forneceu.',

];
